// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  CallReducerFlags,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  DbContext,
  ErrorContextInterface,
  Event,
  EventContextInterface,
  Identity,
  ProductType,
  ProductTypeElement,
  ReducerEventContextInterface,
  SubscriptionBuilderImpl,
  SubscriptionEventContextInterface,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
} from "@clockworklabs/spacetimedb-sdk";
import { DbVector2 as __DbVector2 } from "./db_vector_2_type";

export type BossPhase2Timer = {
  scheduledId: bigint,
  position: __DbVector2,
  scheduledAt: { tag: "Interval", value: TimeDuration } | { tag: "Time", value: Timestamp },
};

/**
 * A namespace for generated helper functions.
 */
export namespace BossPhase2Timer {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("scheduledId", AlgebraicType.createU64Type()),
      new ProductTypeElement("position", __DbVector2.getTypeScriptAlgebraicType()),
      new ProductTypeElement("scheduledAt", AlgebraicType.createScheduleAtType()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: BossPhase2Timer): void {
    BossPhase2Timer.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): BossPhase2Timer {
    return BossPhase2Timer.getTypeScriptAlgebraicType().deserialize(reader);
  }

}


