// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  AccountState,
} from "./types";


export default __t.row({
  identity: __t.identity().primaryKey(),
  name: __t.string(),
  currentPlayerId: __t.u32().name("current_player_id"),
  lastLogin: __t.timestamp().name("last_login"),
  get state() {
    return AccountState;
  },
  soulId: __t.u32().name("soul_id"),
});
