// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  AttackType,
} from "./types";


export default __t.row({
  activeAttackId: __t.u32().primaryKey().name("active_attack_id"),
  entityId: __t.u32().name("entity_id"),
  playerId: __t.u32().name("player_id"),
  get attackType() {
    return AttackType.name("attack_type");
  },
  idWithinBurst: __t.u32().name("id_within_burst"),
  parameterU: __t.u32().name("parameter_u"),
  ticksElapsed: __t.u32().name("ticks_elapsed"),
  damage: __t.u32(),
  radius: __t.f32(),
  piercing: __t.bool(),
});
