// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
import { DbVector2 as __DbVector2 } from "./db_vector_2_type";
import { MonsterAttackType as __MonsterAttackType } from "./monster_attack_type_type";

export type ActiveMonsterAttack = {
  activeMonsterAttackId: bigint,
  scheduledAt: { tag: "Interval", value: TimeDuration } | { tag: "Time", value: Timestamp },
  position: __DbVector2,
  direction: __DbVector2,
  monsterAttackType: __MonsterAttackType,
  piercing: boolean,
  damage: number,
  radius: number,
  speed: number,
  parameterU: number,
  parameterF: number,
  ticksElapsed: number,
  fromShinyMonster: boolean,
};

/**
 * A namespace for generated helper functions.
 */
export namespace ActiveMonsterAttack {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("activeMonsterAttackId", AlgebraicType.createU64Type()),
      new ProductTypeElement("scheduledAt", AlgebraicType.createScheduleAtType()),
      new ProductTypeElement("position", __DbVector2.getTypeScriptAlgebraicType()),
      new ProductTypeElement("direction", __DbVector2.getTypeScriptAlgebraicType()),
      new ProductTypeElement("monsterAttackType", __MonsterAttackType.getTypeScriptAlgebraicType()),
      new ProductTypeElement("piercing", AlgebraicType.createBoolType()),
      new ProductTypeElement("damage", AlgebraicType.createU32Type()),
      new ProductTypeElement("radius", AlgebraicType.createF32Type()),
      new ProductTypeElement("speed", AlgebraicType.createF32Type()),
      new ProductTypeElement("parameterU", AlgebraicType.createU32Type()),
      new ProductTypeElement("parameterF", AlgebraicType.createF32Type()),
      new ProductTypeElement("ticksElapsed", AlgebraicType.createU32Type()),
      new ProductTypeElement("fromShinyMonster", AlgebraicType.createBoolType()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: ActiveMonsterAttack): void {
    ActiveMonsterAttack.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): ActiveMonsterAttack {
    return ActiveMonsterAttack.getTypeScriptAlgebraicType().deserialize(reader);
  }

}


