// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  DbVector2,
  MonsterAttackType,
} from "./types";


export default __t.row({
  activeMonsterAttackId: __t.u64().primaryKey().name("active_monster_attack_id"),
  scheduledAt: __t.scheduleAt().name("scheduled_at"),
  get position() {
    return DbVector2;
  },
  get direction() {
    return DbVector2;
  },
  get monsterAttackType() {
    return MonsterAttackType.name("monster_attack_type");
  },
  piercing: __t.bool(),
  damage: __t.u32(),
  radius: __t.f32(),
  speed: __t.f32(),
  parameterU: __t.u32().name("parameter_u"),
  parameterF: __t.f32().name("parameter_f"),
  ticksElapsed: __t.u32().name("ticks_elapsed"),
  fromShinyMonster: __t.bool().name("from_shiny_monster"),
});
