// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  DbVector2,
} from "./types";


export default __t.row({
  circleId: __t.u64().primaryKey().name("circle_id"),
  bossMonsterId: __t.u32().name("boss_monster_id"),
  targetPlayerId: __t.u32().name("target_player_id"),
  circleIndex: __t.u32().name("circle_index"),
  initialRotation: __t.f32().name("initial_rotation"),
  ticksElapsed: __t.u32().name("ticks_elapsed"),
  get position() {
    return DbVector2;
  },
});
