// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  DbVector2,
} from "./types";


export default __t.row({
  spawnId: __t.u64().primaryKey().name("spawn_id"),
  bossMonsterId: __t.u32().name("boss_monster_id"),
  get position() {
    return DbVector2;
  },
  candleIndex: __t.u32().name("candle_index"),
  candleMonsterId: __t.u32().name("candle_monster_id"),
});
