// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
import { AgnaCandleSpawn } from "./agna_candle_spawn_type";
import { DbVector2 as __DbVector2 } from "./db_vector_2_type";

import { type EventContext, type Reducer, RemoteReducers, RemoteTables } from ".";

/**
 * Table handle for the table `agna_candle_spawns`.
 *
 * Obtain a handle from the [`agnaCandleSpawns`] property on [`RemoteTables`],
 * like `ctx.db.agnaCandleSpawns`.
 *
 * Users are encouraged not to explicitly reference this type,
 * but to directly chain method calls,
 * like `ctx.db.agnaCandleSpawns.on_insert(...)`.
 */
export class AgnaCandleSpawnsTableHandle {
  tableCache: TableCache<AgnaCandleSpawn>;

  constructor(tableCache: TableCache<AgnaCandleSpawn>) {
    this.tableCache = tableCache;
  }

  count(): number {
    return this.tableCache.count();
  }

  iter(): Iterable<AgnaCandleSpawn> {
    return this.tableCache.iter();
  }
  /**
   * Access to the `spawnId` unique index on the table `agna_candle_spawns`,
   * which allows point queries on the field of the same name
   * via the [`AgnaCandleSpawnsSpawnIdUnique.find`] method.
   *
   * Users are encouraged not to explicitly reference this type,
   * but to directly chain method calls,
   * like `ctx.db.agnaCandleSpawns.spawnId().find(...)`.
   *
   * Get a handle on the `spawnId` unique index on the table `agna_candle_spawns`.
   */
  spawnId = {
    // Find the subscribed row whose `spawnId` column value is equal to `col_val`,
    // if such a row is present in the client cache.
    find: (col_val: bigint): AgnaCandleSpawn | undefined => {
      for (let row of this.tableCache.iter()) {
        if (deepEqual(row.spawnId, col_val)) {
          return row;
        }
      }
    },
  };

  onInsert = (cb: (ctx: EventContext, row: AgnaCandleSpawn) => void) => {
    return this.tableCache.onInsert(cb);
  }

  removeOnInsert = (cb: (ctx: EventContext, row: AgnaCandleSpawn) => void) => {
    return this.tableCache.removeOnInsert(cb);
  }

  onDelete = (cb: (ctx: EventContext, row: AgnaCandleSpawn) => void) => {
    return this.tableCache.onDelete(cb);
  }

  removeOnDelete = (cb: (ctx: EventContext, row: AgnaCandleSpawn) => void) => {
    return this.tableCache.removeOnDelete(cb);
  }

  // Updates are only defined for tables with primary keys.
  onUpdate = (cb: (ctx: EventContext, oldRow: AgnaCandleSpawn, newRow: AgnaCandleSpawn) => void) => {
    return this.tableCache.onUpdate(cb);
  }

  removeOnUpdate = (cb: (ctx: EventContext, onRow: AgnaCandleSpawn, newRow: AgnaCandleSpawn) => void) => {
    return this.tableCache.removeOnUpdate(cb);
  }}
