// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
import { DbVector2 as __DbVector2 } from "./db_vector_2_type";

export type AgnaMagicCircle = {
  circleId: bigint,
  bossMonsterId: number,
  targetPlayerId: number,
  circleIndex: number,
  initialRotation: number,
  ticksElapsed: number,
  position: __DbVector2,
};

/**
 * A namespace for generated helper functions.
 */
export namespace AgnaMagicCircle {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("circleId", AlgebraicType.createU64Type()),
      new ProductTypeElement("bossMonsterId", AlgebraicType.createU32Type()),
      new ProductTypeElement("targetPlayerId", AlgebraicType.createU32Type()),
      new ProductTypeElement("circleIndex", AlgebraicType.createU32Type()),
      new ProductTypeElement("initialRotation", AlgebraicType.createF32Type()),
      new ProductTypeElement("ticksElapsed", AlgebraicType.createU32Type()),
      new ProductTypeElement("position", __DbVector2.getTypeScriptAlgebraicType()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: AgnaMagicCircle): void {
    AgnaMagicCircle.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): AgnaMagicCircle {
    return AgnaMagicCircle.getTypeScriptAlgebraicType().deserialize(reader);
  }

}


