// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
} from "spacetimedb";

export type Default = { tag: "Default" };
export type BossEnderIdle = { tag: "BossEnderIdle" };
export type BossEnderChase = { tag: "BossEnderChase" };
export type BossEnderDance = { tag: "BossEnderDance" };
export type BossEnderVanish = { tag: "BossEnderVanish" };
export type BossEnderLurk = { tag: "BossEnderLurk" };
export type BossEnderTeleport = { tag: "BossEnderTeleport" };
export type BossEnderTransform = { tag: "BossEnderTransform" };
export type Stationary = { tag: "Stationary" };
export type BossAgnaIdle = { tag: "BossAgnaIdle" };
export type BossAgnaFlamethrower = { tag: "BossAgnaFlamethrower" };
export type BossAgnaMagicCircle = { tag: "BossAgnaMagicCircle" };
export type BossAgnaRitualMatch = { tag: "BossAgnaRitualMatch" };
export type BossAgnaRitualWick = { tag: "BossAgnaRitualWick" };
export type BossAgnaRitualFailed = { tag: "BossAgnaRitualFailed" };
export type BossAgnaRitualComplete = { tag: "BossAgnaRitualComplete" };
export type BossSimonIdle = { tag: "BossSimonIdle" };
export type BossSimonToxicSpray = { tag: "BossSimonToxicSpray" };
export type BossSimonZombieWave = { tag: "BossSimonZombieWave" };
export type BossSimonTransform = { tag: "BossSimonTransform" };
export type BossSimonChemicalBoltPattern = { tag: "BossSimonChemicalBoltPattern" };
export type BossSimonToxicZonePattern = { tag: "BossSimonToxicZonePattern" };
export type BossSimonPhase2Transform = { tag: "BossSimonPhase2Transform" };

