// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
} from "spacetimedb";
import * as AiStateVariants from './ai_state_variants'

// The tagged union or sum type for the algebraic type `AiState`.
export type AiState = AiStateVariants.Default |
  AiStateVariants.BossEnderIdle |
  AiStateVariants.BossEnderChase |
  AiStateVariants.BossEnderDance |
  AiStateVariants.BossEnderVanish |
  AiStateVariants.BossEnderLurk |
  AiStateVariants.BossEnderTeleport |
  AiStateVariants.BossEnderTransform |
  AiStateVariants.Stationary |
  AiStateVariants.BossAgnaIdle |
  AiStateVariants.BossAgnaFlamethrower |
  AiStateVariants.BossAgnaMagicCircle |
  AiStateVariants.BossAgnaRitualMatch |
  AiStateVariants.BossAgnaRitualWick |
  AiStateVariants.BossAgnaRitualFailed |
  AiStateVariants.BossAgnaRitualComplete |
  AiStateVariants.BossSimonIdle |
  AiStateVariants.BossSimonToxicSpray |
  AiStateVariants.BossSimonZombieWave |
  AiStateVariants.BossSimonTransform |
  AiStateVariants.BossSimonChemicalBoltPattern |
  AiStateVariants.BossSimonToxicZonePattern |
  AiStateVariants.BossSimonPhase2Transform;

// A value with helper functions to construct the type.
export const AiState = {
  // Helper functions for constructing each variant of the tagged union.
  // ```
  // const foo = Foo.A(42);
  // assert!(foo.tag === "A");
  // assert!(foo.value === 42);
  // ```
  Default: { tag: "Default" } as const,
  BossEnderIdle: { tag: "BossEnderIdle" } as const,
  BossEnderChase: { tag: "BossEnderChase" } as const,
  BossEnderDance: { tag: "BossEnderDance" } as const,
  BossEnderVanish: { tag: "BossEnderVanish" } as const,
  BossEnderLurk: { tag: "BossEnderLurk" } as const,
  BossEnderTeleport: { tag: "BossEnderTeleport" } as const,
  BossEnderTransform: { tag: "BossEnderTransform" } as const,
  Stationary: { tag: "Stationary" } as const,
  BossAgnaIdle: { tag: "BossAgnaIdle" } as const,
  BossAgnaFlamethrower: { tag: "BossAgnaFlamethrower" } as const,
  BossAgnaMagicCircle: { tag: "BossAgnaMagicCircle" } as const,
  BossAgnaRitualMatch: { tag: "BossAgnaRitualMatch" } as const,
  BossAgnaRitualWick: { tag: "BossAgnaRitualWick" } as const,
  BossAgnaRitualFailed: { tag: "BossAgnaRitualFailed" } as const,
  BossAgnaRitualComplete: { tag: "BossAgnaRitualComplete" } as const,
  BossSimonIdle: { tag: "BossSimonIdle" } as const,
  BossSimonToxicSpray: { tag: "BossSimonToxicSpray" } as const,
  BossSimonZombieWave: { tag: "BossSimonZombieWave" } as const,
  BossSimonTransform: { tag: "BossSimonTransform" } as const,
  BossSimonChemicalBoltPattern: { tag: "BossSimonChemicalBoltPattern" } as const,
  BossSimonToxicZonePattern: { tag: "BossSimonToxicZonePattern" } as const,
  BossSimonPhase2Transform: { tag: "BossSimonPhase2Transform" } as const,

  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    return __AlgebraicTypeValue.Sum({
      variants: [
        { name: "Default", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "BossEnderIdle", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "BossEnderChase", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "BossEnderDance", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "BossEnderVanish", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "BossEnderLurk", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "BossEnderTeleport", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "BossEnderTransform", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "Stationary", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "BossAgnaIdle", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "BossAgnaFlamethrower", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "BossAgnaMagicCircle", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "BossAgnaRitualMatch", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "BossAgnaRitualWick", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "BossAgnaRitualFailed", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "BossAgnaRitualComplete", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "BossSimonIdle", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "BossSimonToxicSpray", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "BossSimonZombieWave", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "BossSimonTransform", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "BossSimonChemicalBoltPattern", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "BossSimonToxicZonePattern", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "BossSimonPhase2Transform", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
      ]
    });
  },

  serialize(writer: __BinaryWriter, value: AiState): void {
      __AlgebraicTypeValue.serializeValue(writer, AiState.getTypeScriptAlgebraicType(), value);
  },

  deserialize(reader: __BinaryReader): AiState {
      return __AlgebraicTypeValue.deserializeValue(reader, AiState.getTypeScriptAlgebraicType());
  },

}

export default AiState;


