// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
} from "spacetimedb";
import * as AttackTypeVariants from './attack_type_variants'

// The tagged union or sum type for the algebraic type `AttackType`.
export type AttackType = AttackTypeVariants.Sword |
  AttackTypeVariants.Wand |
  AttackTypeVariants.Knives |
  AttackTypeVariants.Shield |
  AttackTypeVariants.ThunderHorn |
  AttackTypeVariants.AngelStaff |
  AttackTypeVariants.Football |
  AttackTypeVariants.Cards |
  AttackTypeVariants.Dumbbell |
  AttackTypeVariants.Garlic |
  AttackTypeVariants.Volleyball |
  AttackTypeVariants.Joint;

// A value with helper functions to construct the type.
export const AttackType = {
  // Helper functions for constructing each variant of the tagged union.
  // ```
  // const foo = Foo.A(42);
  // assert!(foo.tag === "A");
  // assert!(foo.value === 42);
  // ```
  Sword: { tag: "Sword" } as const,
  Wand: { tag: "Wand" } as const,
  Knives: { tag: "Knives" } as const,
  Shield: { tag: "Shield" } as const,
  ThunderHorn: { tag: "ThunderHorn" } as const,
  AngelStaff: { tag: "AngelStaff" } as const,
  Football: { tag: "Football" } as const,
  Cards: { tag: "Cards" } as const,
  Dumbbell: { tag: "Dumbbell" } as const,
  Garlic: { tag: "Garlic" } as const,
  Volleyball: { tag: "Volleyball" } as const,
  Joint: { tag: "Joint" } as const,

  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    return __AlgebraicTypeValue.Sum({
      variants: [
        { name: "Sword", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "Wand", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "Knives", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "Shield", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "ThunderHorn", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "AngelStaff", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "Football", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "Cards", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "Dumbbell", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "Garlic", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "Volleyball", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "Joint", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
      ]
    });
  },

  serialize(writer: __BinaryWriter, value: AttackType): void {
      __AlgebraicTypeValue.serializeValue(writer, AttackType.getTypeScriptAlgebraicType(), value);
  },

  deserialize(reader: __BinaryReader): AttackType {
      return __AlgebraicTypeValue.deserializeValue(reader, AttackType.getTypeScriptAlgebraicType());
  },

}

export default AttackType;


