// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  AttackType,
} from "./types";


export default __t.row({
  scheduledId: __t.u64().primaryKey().name("scheduled_id"),
  playerId: __t.u32().name("player_id"),
  get attackType() {
    return AttackType.name("attack_type");
  },
  remainingShots: __t.u32().name("remaining_shots"),
  parameterU: __t.u32().name("parameter_u"),
  parameterI: __t.i32().name("parameter_i"),
  scheduledAt: __t.scheduleAt().name("scheduled_at"),
});
