// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  AttackType,
} from "./types";


export default __t.row({
  attackId: __t.u32().primaryKey().name("attack_id"),
  get attackType() {
    return AttackType.name("attack_type");
  },
  name: __t.string(),
  cooldown: __t.u32(),
  duration: __t.u32(),
  projectiles: __t.u32(),
  fireDelay: __t.u32().name("fire_delay"),
  speed: __t.f32(),
  piercing: __t.bool(),
  radius: __t.f32(),
  damage: __t.u32(),
  armorPiercing: __t.u32().name("armor_piercing"),
});
