// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
import { MonsterType as __MonsterType } from "./monster_type_type";

export type Bestiary = {
  bestiaryId: number,
  monsterType: __MonsterType,
  tier: number,
  maxHp: number,
  speed: number,
  atk: number,
  radius: number,
};

/**
 * A namespace for generated helper functions.
 */
export namespace Bestiary {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("bestiaryId", AlgebraicType.createU32Type()),
      new ProductTypeElement("monsterType", __MonsterType.getTypeScriptAlgebraicType()),
      new ProductTypeElement("tier", AlgebraicType.createU32Type()),
      new ProductTypeElement("maxHp", AlgebraicType.createU32Type()),
      new ProductTypeElement("speed", AlgebraicType.createF32Type()),
      new ProductTypeElement("atk", AlgebraicType.createF32Type()),
      new ProductTypeElement("radius", AlgebraicType.createF32Type()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: Bestiary): void {
    Bestiary.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): Bestiary {
    return Bestiary.getTypeScriptAlgebraicType().deserialize(reader);
  }

}


