// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
} from "spacetimedb";
import { BossAgnaLastPattern } from "./boss_agna_last_pattern_type";
import { AiState } from "./ai_state_type";
// Mark import as potentially unused
declare type __keep_AiState = AiState;

import { type EventContext, type Reducer, RemoteReducers, RemoteTables } from ".";
declare type __keep = [EventContext, Reducer, RemoteReducers, RemoteTables];

/**
 * Table handle for the table `boss_agna_last_patterns`.
 *
 * Obtain a handle from the [`bossAgnaLastPatterns`] property on [`RemoteTables`],
 * like `ctx.db.bossAgnaLastPatterns`.
 *
 * Users are encouraged not to explicitly reference this type,
 * but to directly chain method calls,
 * like `ctx.db.bossAgnaLastPatterns.on_insert(...)`.
 */
export class BossAgnaLastPatternsTableHandle {
  tableCache: __TableCache<BossAgnaLastPattern>;

  constructor(tableCache: __TableCache<BossAgnaLastPattern>) {
    this.tableCache = tableCache;
  }

  count(): number {
    return this.tableCache.count();
  }

  iter(): Iterable<BossAgnaLastPattern> {
    return this.tableCache.iter();
  }
  /**
   * Access to the `monsterId` unique index on the table `boss_agna_last_patterns`,
   * which allows point queries on the field of the same name
   * via the [`BossAgnaLastPatternsMonsterIdUnique.find`] method.
   *
   * Users are encouraged not to explicitly reference this type,
   * but to directly chain method calls,
   * like `ctx.db.bossAgnaLastPatterns.monsterId().find(...)`.
   *
   * Get a handle on the `monsterId` unique index on the table `boss_agna_last_patterns`.
   */
  monsterId = {
    // Find the subscribed row whose `monsterId` column value is equal to `col_val`,
    // if such a row is present in the client cache.
    find: (col_val: number): BossAgnaLastPattern | undefined => {
      for (let row of this.tableCache.iter()) {
        if (__deepEqual(row.monsterId, col_val)) {
          return row;
        }
      }
    },
  };

  onInsert = (cb: (ctx: EventContext, row: BossAgnaLastPattern) => void) => {
    return this.tableCache.onInsert(cb);
  }

  removeOnInsert = (cb: (ctx: EventContext, row: BossAgnaLastPattern) => void) => {
    return this.tableCache.removeOnInsert(cb);
  }

  onDelete = (cb: (ctx: EventContext, row: BossAgnaLastPattern) => void) => {
    return this.tableCache.onDelete(cb);
  }

  removeOnDelete = (cb: (ctx: EventContext, row: BossAgnaLastPattern) => void) => {
    return this.tableCache.removeOnDelete(cb);
  }

  // Updates are only defined for tables with primary keys.
  onUpdate = (cb: (ctx: EventContext, oldRow: BossAgnaLastPattern, newRow: BossAgnaLastPattern) => void) => {
    return this.tableCache.onUpdate(cb);
  }

  removeOnUpdate = (cb: (ctx: EventContext, onRow: BossAgnaLastPattern, newRow: BossAgnaLastPattern) => void) => {
    return this.tableCache.removeOnUpdate(cb);
  }}
