// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
import { UpgradeType as __UpgradeType } from "./upgrade_type_type";

export type ChosenUpgradeData = {
  chosenUpgradeId: number,
  playerId: number,
  upgradeType: __UpgradeType,
  isAttackUpgrade: boolean,
  value: number,
  attackType: number,
  damage: number,
  cooldownRatio: number,
  projectiles: number,
  speed: number,
  radius: number,
  isNewAttack: boolean,
};

/**
 * A namespace for generated helper functions.
 */
export namespace ChosenUpgradeData {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("chosenUpgradeId", AlgebraicType.createU32Type()),
      new ProductTypeElement("playerId", AlgebraicType.createU32Type()),
      new ProductTypeElement("upgradeType", __UpgradeType.getTypeScriptAlgebraicType()),
      new ProductTypeElement("isAttackUpgrade", AlgebraicType.createBoolType()),
      new ProductTypeElement("value", AlgebraicType.createU32Type()),
      new ProductTypeElement("attackType", AlgebraicType.createU32Type()),
      new ProductTypeElement("damage", AlgebraicType.createU32Type()),
      new ProductTypeElement("cooldownRatio", AlgebraicType.createU32Type()),
      new ProductTypeElement("projectiles", AlgebraicType.createU32Type()),
      new ProductTypeElement("speed", AlgebraicType.createU32Type()),
      new ProductTypeElement("radius", AlgebraicType.createU32Type()),
      new ProductTypeElement("isNewAttack", AlgebraicType.createBoolType()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: ChosenUpgradeData): void {
    ChosenUpgradeData.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): ChosenUpgradeData {
    return ChosenUpgradeData.getTypeScriptAlgebraicType().deserialize(reader);
  }

}


