// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
} from "spacetimedb";
import { ChosenUpgradeData } from "./chosen_upgrade_data_type";
import { UpgradeType } from "./upgrade_type_type";
// Mark import as potentially unused
declare type __keep_UpgradeType = UpgradeType;

import { type EventContext, type Reducer, RemoteReducers, RemoteTables } from ".";
declare type __keep = [EventContext, Reducer, RemoteReducers, RemoteTables];

/**
 * Table handle for the table `chosen_upgrades`.
 *
 * Obtain a handle from the [`chosenUpgrades`] property on [`RemoteTables`],
 * like `ctx.db.chosenUpgrades`.
 *
 * Users are encouraged not to explicitly reference this type,
 * but to directly chain method calls,
 * like `ctx.db.chosenUpgrades.on_insert(...)`.
 */
export class ChosenUpgradesTableHandle {
  tableCache: __TableCache<ChosenUpgradeData>;

  constructor(tableCache: __TableCache<ChosenUpgradeData>) {
    this.tableCache = tableCache;
  }

  count(): number {
    return this.tableCache.count();
  }

  iter(): Iterable<ChosenUpgradeData> {
    return this.tableCache.iter();
  }
  /**
   * Access to the `chosenUpgradeId` unique index on the table `chosen_upgrades`,
   * which allows point queries on the field of the same name
   * via the [`ChosenUpgradesChosenUpgradeIdUnique.find`] method.
   *
   * Users are encouraged not to explicitly reference this type,
   * but to directly chain method calls,
   * like `ctx.db.chosenUpgrades.chosenUpgradeId().find(...)`.
   *
   * Get a handle on the `chosenUpgradeId` unique index on the table `chosen_upgrades`.
   */
  chosenUpgradeId = {
    // Find the subscribed row whose `chosenUpgradeId` column value is equal to `col_val`,
    // if such a row is present in the client cache.
    find: (col_val: number): ChosenUpgradeData | undefined => {
      for (let row of this.tableCache.iter()) {
        if (__deepEqual(row.chosenUpgradeId, col_val)) {
          return row;
        }
      }
    },
  };

  onInsert = (cb: (ctx: EventContext, row: ChosenUpgradeData) => void) => {
    return this.tableCache.onInsert(cb);
  }

  removeOnInsert = (cb: (ctx: EventContext, row: ChosenUpgradeData) => void) => {
    return this.tableCache.removeOnInsert(cb);
  }

  onDelete = (cb: (ctx: EventContext, row: ChosenUpgradeData) => void) => {
    return this.tableCache.onDelete(cb);
  }

  removeOnDelete = (cb: (ctx: EventContext, row: ChosenUpgradeData) => void) => {
    return this.tableCache.removeOnDelete(cb);
  }

  // Updates are only defined for tables with primary keys.
  onUpdate = (cb: (ctx: EventContext, oldRow: ChosenUpgradeData, newRow: ChosenUpgradeData) => void) => {
    return this.tableCache.onUpdate(cb);
  }

  removeOnUpdate = (cb: (ctx: EventContext, onRow: ChosenUpgradeData, newRow: ChosenUpgradeData) => void) => {
    return this.tableCache.removeOnUpdate(cb);
  }}
