// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  AttackType,
  PlayerClass,
} from "./types";


export default __t.row({
  classId: __t.u32().primaryKey().name("class_id"),
  get playerClass() {
    return PlayerClass.name("player_class");
  },
  maxHp: __t.i32().name("max_hp"),
  armor: __t.i32(),
  speed: __t.f32(),
  get startingAttackType() {
    return AttackType.name("starting_attack_type");
  },
});
