// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
import { AttackType as __AttackType } from "./attack_type_type";
import { PlayerClass as __PlayerClass } from "./player_class_type";

export type ClassData = {
  classId: number,
  playerClass: __PlayerClass,
  maxHp: number,
  armor: number,
  speed: number,
  startingAttackType: __AttackType,
};

/**
 * A namespace for generated helper functions.
 */
export namespace ClassData {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("classId", AlgebraicType.createU32Type()),
      new ProductTypeElement("playerClass", __PlayerClass.getTypeScriptAlgebraicType()),
      new ProductTypeElement("maxHp", AlgebraicType.createI32Type()),
      new ProductTypeElement("armor", AlgebraicType.createI32Type()),
      new ProductTypeElement("speed", AlgebraicType.createF32Type()),
      new ProductTypeElement("startingAttackType", __AttackType.getTypeScriptAlgebraicType()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: ClassData): void {
    ClassData.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): ClassData {
    return ClassData.getTypeScriptAlgebraicType().deserialize(reader);
  }

}


