// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  CallReducerFlags,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  DbContext,
  ErrorContextInterface,
  Event,
  EventContextInterface,
  Identity,
  ProductType,
  ProductTypeElement,
  ReducerEventContextInterface,
  SubscriptionBuilderImpl,
  SubscriptionEventContextInterface,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
} from "@clockworklabs/spacetimedb-sdk";
import { ClassData } from "./class_data_type";
import { AttackType as __AttackType } from "./attack_type_type";
import { PlayerClass as __PlayerClass } from "./player_class_type";

import { EventContext, Reducer, RemoteReducers, RemoteTables } from ".";

/**
 * Table handle for the table `class_data`.
 *
 * Obtain a handle from the [`classData`] property on [`RemoteTables`],
 * like `ctx.db.classData`.
 *
 * Users are encouraged not to explicitly reference this type,
 * but to directly chain method calls,
 * like `ctx.db.classData.on_insert(...)`.
 */
export class ClassDataTableHandle {
  tableCache: TableCache<ClassData>;

  constructor(tableCache: TableCache<ClassData>) {
    this.tableCache = tableCache;
  }

  count(): number {
    return this.tableCache.count();
  }

  iter(): Iterable<ClassData> {
    return this.tableCache.iter();
  }
  /**
   * Access to the `classId` unique index on the table `class_data`,
   * which allows point queries on the field of the same name
   * via the [`ClassDataClassIdUnique.find`] method.
   *
   * Users are encouraged not to explicitly reference this type,
   * but to directly chain method calls,
   * like `ctx.db.classData.classId().find(...)`.
   *
   * Get a handle on the `classId` unique index on the table `class_data`.
   */
  classId = {
    // Find the subscribed row whose `classId` column value is equal to `col_val`,
    // if such a row is present in the client cache.
    find: (col_val: number): ClassData | undefined => {
      for (let row of this.tableCache.iter()) {
        if (deepEqual(row.classId, col_val)) {
          return row;
        }
      }
    },
  };

  onInsert = (cb: (ctx: EventContext, row: ClassData) => void) => {
    return this.tableCache.onInsert(cb);
  }

  removeOnInsert = (cb: (ctx: EventContext, row: ClassData) => void) => {
    return this.tableCache.removeOnInsert(cb);
  }

  onDelete = (cb: (ctx: EventContext, row: ClassData) => void) => {
    return this.tableCache.onDelete(cb);
  }

  removeOnDelete = (cb: (ctx: EventContext, row: ClassData) => void) => {
    return this.tableCache.removeOnDelete(cb);
  }

  // Updates are only defined for tables with primary keys.
  onUpdate = (cb: (ctx: EventContext, oldRow: ClassData, newRow: ClassData) => void) => {
    return this.tableCache.onUpdate(cb);
  }

  removeOnUpdate = (cb: (ctx: EventContext, onRow: ClassData, newRow: ClassData) => void) => {
    return this.tableCache.removeOnUpdate(cb);
  }}
