// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u32().primaryKey(),
  worldSize: __t.u32().name("world_size"),
  gameTickRate: __t.u32().name("game_tick_rate"),
  maxMonsters: __t.u32().name("max_monsters"),
  playerSpawnGracePeriod: __t.u32().name("player_spawn_grace_period"),
  monsterHitCleanupDelay: __t.u32().name("monster_hit_cleanup_delay"),
  monsterWaveSize: __t.u32().name("monster_wave_size"),
});
