// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
} from "spacetimedb";
import * as CurseTypeVariants from './curse_type_variants'

// The tagged union or sum type for the algebraic type `CurseType`.
export type CurseType = CurseTypeVariants.MonsterMoreHp |
  CurseTypeVariants.MonsterMoreDamage |
  CurseTypeVariants.MonsterMoreSpeed |
  CurseTypeVariants.MonsterHealthRegen |
  CurseTypeVariants.CursedMonstersSpawn |
  CurseTypeVariants.NoFreeReroll |
  CurseTypeVariants.NoHealOnLevelUp |
  CurseTypeVariants.NegativeHealthRegen |
  CurseTypeVariants.PlayersStartLessHp |
  CurseTypeVariants.PlayersStartLessSpeed |
  CurseTypeVariants.NoDiceDrops |
  CurseTypeVariants.NoFoodDrops |
  CurseTypeVariants.NoBoosterPackDrops |
  CurseTypeVariants.NoStructureLoot |
  CurseTypeVariants.OneLessVoidChest |
  CurseTypeVariants.OneLessVoidChestSecond |
  CurseTypeVariants.MonstersDropFewerGems |
  CurseTypeVariants.BossAppearsSooner |
  CurseTypeVariants.DeadlierBosses |
  CurseTypeVariants.DeadlierBossesTwo |
  CurseTypeVariants.Scaling;

// A value with helper functions to construct the type.
export const CurseType = {
  // Helper functions for constructing each variant of the tagged union.
  // ```
  // const foo = Foo.A(42);
  // assert!(foo.tag === "A");
  // assert!(foo.value === 42);
  // ```
  MonsterMoreHp: { tag: "MonsterMoreHp" } as const,
  MonsterMoreDamage: { tag: "MonsterMoreDamage" } as const,
  MonsterMoreSpeed: { tag: "MonsterMoreSpeed" } as const,
  MonsterHealthRegen: { tag: "MonsterHealthRegen" } as const,
  CursedMonstersSpawn: { tag: "CursedMonstersSpawn" } as const,
  NoFreeReroll: { tag: "NoFreeReroll" } as const,
  NoHealOnLevelUp: { tag: "NoHealOnLevelUp" } as const,
  NegativeHealthRegen: { tag: "NegativeHealthRegen" } as const,
  PlayersStartLessHp: { tag: "PlayersStartLessHp" } as const,
  PlayersStartLessSpeed: { tag: "PlayersStartLessSpeed" } as const,
  NoDiceDrops: { tag: "NoDiceDrops" } as const,
  NoFoodDrops: { tag: "NoFoodDrops" } as const,
  NoBoosterPackDrops: { tag: "NoBoosterPackDrops" } as const,
  NoStructureLoot: { tag: "NoStructureLoot" } as const,
  OneLessVoidChest: { tag: "OneLessVoidChest" } as const,
  OneLessVoidChestSecond: { tag: "OneLessVoidChestSecond" } as const,
  MonstersDropFewerGems: { tag: "MonstersDropFewerGems" } as const,
  BossAppearsSooner: { tag: "BossAppearsSooner" } as const,
  DeadlierBosses: { tag: "DeadlierBosses" } as const,
  DeadlierBossesTwo: { tag: "DeadlierBossesTwo" } as const,
  Scaling: { tag: "Scaling" } as const,

  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    return __AlgebraicTypeValue.Sum({
      variants: [
        { name: "MonsterMoreHp", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "MonsterMoreDamage", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "MonsterMoreSpeed", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "MonsterHealthRegen", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "CursedMonstersSpawn", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "NoFreeReroll", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "NoHealOnLevelUp", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "NegativeHealthRegen", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "PlayersStartLessHp", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "PlayersStartLessSpeed", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "NoDiceDrops", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "NoFoodDrops", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "NoBoosterPackDrops", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "NoStructureLoot", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "OneLessVoidChest", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "OneLessVoidChestSecond", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "MonstersDropFewerGems", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "BossAppearsSooner", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "DeadlierBosses", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "DeadlierBossesTwo", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "Scaling", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
      ]
    });
  },

  serialize(writer: __BinaryWriter, value: CurseType): void {
      __AlgebraicTypeValue.serializeValue(writer, CurseType.getTypeScriptAlgebraicType(), value);
  },

  deserialize(reader: __BinaryReader): CurseType {
      return __AlgebraicTypeValue.deserializeValue(reader, CurseType.getTypeScriptAlgebraicType());
  },

}

export default CurseType;


