// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
} from "spacetimedb";

export type MonsterMoreHp = { tag: "MonsterMoreHp" };
export type MonsterMoreDamage = { tag: "MonsterMoreDamage" };
export type MonsterMoreSpeed = { tag: "MonsterMoreSpeed" };
export type MonsterHealthRegen = { tag: "MonsterHealthRegen" };
export type CursedMonstersSpawn = { tag: "CursedMonstersSpawn" };
export type NoFreeReroll = { tag: "NoFreeReroll" };
export type NoHealOnLevelUp = { tag: "NoHealOnLevelUp" };
export type NegativeHealthRegen = { tag: "NegativeHealthRegen" };
export type PlayersStartLessHp = { tag: "PlayersStartLessHp" };
export type PlayersStartLessSpeed = { tag: "PlayersStartLessSpeed" };
export type NoDiceDrops = { tag: "NoDiceDrops" };
export type NoFoodDrops = { tag: "NoFoodDrops" };
export type NoBoosterPackDrops = { tag: "NoBoosterPackDrops" };
export type NoStructureLoot = { tag: "NoStructureLoot" };
export type OneLessVoidChest = { tag: "OneLessVoidChest" };
export type OneLessVoidChestSecond = { tag: "OneLessVoidChestSecond" };
export type MonstersDropFewerGems = { tag: "MonstersDropFewerGems" };
export type BossAppearsSooner = { tag: "BossAppearsSooner" };
export type DeadlierBosses = { tag: "DeadlierBosses" };
export type DeadlierBossesTwo = { tag: "DeadlierBossesTwo" };
export type Scaling = { tag: "Scaling" };

