// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  DbVector2,
} from "./types";


export default __t.row({
  entityId: __t.u32().primaryKey().name("entity_id"),
  get position() {
    return DbVector2;
  },
  get direction() {
    return DbVector2;
  },
  radius: __t.f32(),
  get waypoint() {
    return DbVector2;
  },
  hasWaypoint: __t.bool().name("has_waypoint"),
});
