// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  configId: __t.u32().primaryKey().name("config_id"),
  expSmallGem: __t.u32().name("exp_small_gem"),
  expMediumGem: __t.u32().name("exp_medium_gem"),
  expLargeGem: __t.u32().name("exp_large_gem"),
  expHugeGem: __t.u32().name("exp_huge_gem"),
  baseExpPerLevel: __t.u32().name("base_exp_per_level"),
  levelExpFactor: __t.f32().name("level_exp_factor"),
  gemRadius: __t.f32().name("gem_radius"),
});
