// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  CallReducerFlags,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  DbContext,
  ErrorContextInterface,
  Event,
  EventContextInterface,
  Identity,
  ProductType,
  ProductTypeElement,
  ReducerEventContextInterface,
  SubscriptionBuilderImpl,
  SubscriptionEventContextInterface,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
} from "@clockworklabs/spacetimedb-sdk";
export type ExpConfig = {
  configId: number,
  expSmallGem: number,
  expMediumGem: number,
  expLargeGem: number,
  expHugeGem: number,
  baseExpPerLevel: number,
  levelExpFactor: number,
  gemRadius: number,
};

/**
 * A namespace for generated helper functions.
 */
export namespace ExpConfig {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("configId", AlgebraicType.createU32Type()),
      new ProductTypeElement("expSmallGem", AlgebraicType.createU32Type()),
      new ProductTypeElement("expMediumGem", AlgebraicType.createU32Type()),
      new ProductTypeElement("expLargeGem", AlgebraicType.createU32Type()),
      new ProductTypeElement("expHugeGem", AlgebraicType.createU32Type()),
      new ProductTypeElement("baseExpPerLevel", AlgebraicType.createU32Type()),
      new ProductTypeElement("levelExpFactor", AlgebraicType.createF32Type()),
      new ProductTypeElement("gemRadius", AlgebraicType.createF32Type()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: ExpConfig): void {
    ExpConfig.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): ExpConfig {
    return ExpConfig.getTypeScriptAlgebraicType().deserialize(reader);
  }

}


