// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
import { BossType as __BossType } from "./boss_type_type";

export type GameState = {
  id: number,
  bossActive: boolean,
  bossPhase: number,
  bossMonsterId: number,
  bossType: __BossType,
  normalSpawningPaused: boolean,
  gameStartTime: Timestamp,
};

/**
 * A namespace for generated helper functions.
 */
export namespace GameState {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("id", AlgebraicType.createU32Type()),
      new ProductTypeElement("bossActive", AlgebraicType.createBoolType()),
      new ProductTypeElement("bossPhase", AlgebraicType.createU32Type()),
      new ProductTypeElement("bossMonsterId", AlgebraicType.createU32Type()),
      new ProductTypeElement("bossType", __BossType.getTypeScriptAlgebraicType()),
      new ProductTypeElement("normalSpawningPaused", AlgebraicType.createBoolType()),
      new ProductTypeElement("gameStartTime", AlgebraicType.createTimestampType()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: GameState): void {
    GameState.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): GameState {
    return GameState.getTypeScriptAlgebraicType().deserialize(reader);
  }

}


