// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
} from "spacetimedb";
import * as GemLevelVariants from './gem_level_variants'

// The tagged union or sum type for the algebraic type `GemLevel`.
export type GemLevel = GemLevelVariants.Small |
  GemLevelVariants.Medium |
  GemLevelVariants.Large |
  GemLevelVariants.Huge |
  GemLevelVariants.Soul |
  GemLevelVariants.Fries |
  GemLevelVariants.Dice |
  GemLevelVariants.BoosterPack |
  GemLevelVariants.LoreScroll;

// A value with helper functions to construct the type.
export const GemLevel = {
  // Helper functions for constructing each variant of the tagged union.
  // ```
  // const foo = Foo.A(42);
  // assert!(foo.tag === "A");
  // assert!(foo.value === 42);
  // ```
  Small: { tag: "Small" } as const,
  Medium: { tag: "Medium" } as const,
  Large: { tag: "Large" } as const,
  Huge: { tag: "Huge" } as const,
  Soul: { tag: "Soul" } as const,
  Fries: { tag: "Fries" } as const,
  Dice: { tag: "Dice" } as const,
  BoosterPack: { tag: "BoosterPack" } as const,
  LoreScroll: { tag: "LoreScroll" } as const,

  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    return __AlgebraicTypeValue.Sum({
      variants: [
        { name: "Small", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "Medium", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "Large", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "Huge", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "Soul", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "Fries", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "Dice", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "BoosterPack", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "LoreScroll", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
      ]
    });
  },

  serialize(writer: __BinaryWriter, value: GemLevel): void {
      __AlgebraicTypeValue.serializeValue(writer, GemLevel.getTypeScriptAlgebraicType(), value);
  },

  deserialize(reader: __BinaryReader): GemLevel {
      return __AlgebraicTypeValue.deserializeValue(reader, GemLevel.getTypeScriptAlgebraicType());
  },

}

export default GemLevel;


