// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
import { Gem } from "./gem_type";
import { GemLevel as __GemLevel } from "./gem_level_type";

import { type EventContext, type Reducer, RemoteReducers, RemoteTables } from ".";

/**
 * Table handle for the table `gems`.
 *
 * Obtain a handle from the [`gems`] property on [`RemoteTables`],
 * like `ctx.db.gems`.
 *
 * Users are encouraged not to explicitly reference this type,
 * but to directly chain method calls,
 * like `ctx.db.gems.on_insert(...)`.
 */
export class GemsTableHandle {
  tableCache: TableCache<Gem>;

  constructor(tableCache: TableCache<Gem>) {
    this.tableCache = tableCache;
  }

  count(): number {
    return this.tableCache.count();
  }

  iter(): Iterable<Gem> {
    return this.tableCache.iter();
  }
  /**
   * Access to the `gemId` unique index on the table `gems`,
   * which allows point queries on the field of the same name
   * via the [`GemsGemIdUnique.find`] method.
   *
   * Users are encouraged not to explicitly reference this type,
   * but to directly chain method calls,
   * like `ctx.db.gems.gemId().find(...)`.
   *
   * Get a handle on the `gemId` unique index on the table `gems`.
   */
  gemId = {
    // Find the subscribed row whose `gemId` column value is equal to `col_val`,
    // if such a row is present in the client cache.
    find: (col_val: number): Gem | undefined => {
      for (let row of this.tableCache.iter()) {
        if (deepEqual(row.gemId, col_val)) {
          return row;
        }
      }
    },
  };
  /**
   * Access to the `entityId` unique index on the table `gems`,
   * which allows point queries on the field of the same name
   * via the [`GemsEntityIdUnique.find`] method.
   *
   * Users are encouraged not to explicitly reference this type,
   * but to directly chain method calls,
   * like `ctx.db.gems.entityId().find(...)`.
   *
   * Get a handle on the `entityId` unique index on the table `gems`.
   */
  entityId = {
    // Find the subscribed row whose `entityId` column value is equal to `col_val`,
    // if such a row is present in the client cache.
    find: (col_val: number): Gem | undefined => {
      for (let row of this.tableCache.iter()) {
        if (deepEqual(row.entityId, col_val)) {
          return row;
        }
      }
    },
  };

  onInsert = (cb: (ctx: EventContext, row: Gem) => void) => {
    return this.tableCache.onInsert(cb);
  }

  removeOnInsert = (cb: (ctx: EventContext, row: Gem) => void) => {
    return this.tableCache.removeOnInsert(cb);
  }

  onDelete = (cb: (ctx: EventContext, row: Gem) => void) => {
    return this.tableCache.onDelete(cb);
  }

  removeOnDelete = (cb: (ctx: EventContext, row: Gem) => void) => {
    return this.tableCache.removeOnDelete(cb);
  }

  // Updates are only defined for tables with primary keys.
  onUpdate = (cb: (ctx: EventContext, oldRow: Gem, newRow: Gem) => void) => {
    return this.tableCache.onUpdate(cb);
  }

  removeOnUpdate = (cb: (ctx: EventContext, onRow: Gem, newRow: Gem) => void) => {
    return this.tableCache.removeOnUpdate(cb);
  }}
