// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.1.0 (commit 6981f48b4bc1a71c8dd9bdfe5a2c343f6370243d).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import all reducer arg schemas
import AdminAddCurseReducer from "./admin_add_curse_reducer";
import AdminAddDebugCurseReducer from "./admin_add_debug_curse_reducer";
import AdminClearCursesReducer from "./admin_clear_curses_reducer";
import ChooseUpgradeReducer from "./choose_upgrade_reducer";
import CleanupGameStateReducer from "./cleanup_game_state_reducer";
import DebugCheckGemDropsReducer from "./debug_check_gem_drops_reducer";
import DebugCheckTierReducer from "./debug_check_tier_reducer";
import DebugEnableBotPvpReducer from "./debug_enable_bot_pvp_reducer";
import DebugSetBossTypeReducer from "./debug_set_boss_type_reducer";
import DebugSetSuperHealthReducer from "./debug_set_super_health_reducer";
import InitAttackDataReducer from "./init_attack_data_reducer";
import InitHealthRegenSystemReducer from "./init_health_regen_system_reducer";
import LoadBuildReducer from "./load_build_reducer";
import RerollUpgradesReducer from "./reroll_upgrades_reducer";
import ResetWorldReducer from "./reset_world_reducer";
import SaveBuildReducer from "./save_build_reducer";
import SetNameReducer from "./set_name_reducer";
import SetPlayerPvpModeReducer from "./set_player_pvp_mode_reducer";
import SetPlayerWaypointReducer from "./set_player_waypoint_reducer";
import SpawnBossForTestingReducer from "./spawn_boss_for_testing_reducer";
import SpawnBotReducer from "./spawn_bot_reducer";
import SpawnDebugLootCapsuleReducer from "./spawn_debug_loot_capsule_reducer";
import SpawnDebugLoreScrollReducer from "./spawn_debug_lore_scroll_reducer";
import SpawnDebugSpecialGemReducer from "./spawn_debug_special_gem_reducer";
import SpawnDebugVoidChestReducer from "./spawn_debug_void_chest_reducer";
import SpawnPlayerReducer from "./spawn_player_reducer";
import UpdateLastLoginReducer from "./update_last_login_reducer";

// Import all procedure arg schemas

// Import all table schema definitions
import AccountRow from "./account_table";
import ActiveAttackCleanupRow from "./active_attack_cleanup_table";
import ActiveAttacksRow from "./active_attacks_table";
import ActiveMonsterAttacksRow from "./active_monster_attacks_table";
import AgnaCandleBoltSchedulerRow from "./agna_candle_bolt_scheduler_table";
import AgnaCandleSchedulerRow from "./agna_candle_scheduler_table";
import AgnaCandleSpawnsRow from "./agna_candle_spawns_table";
import AgnaDelayedOrbSchedulerRow from "./agna_delayed_orb_scheduler_table";
import AgnaFireOrbSchedulerRow from "./agna_fire_orb_scheduler_table";
import AgnaFlamethrowerSchedulerRow from "./agna_flamethrower_scheduler_table";
import AgnaMagicCirclesRow from "./agna_magic_circles_table";
import AgnaPhase2FlamethrowerSchedulerRow from "./agna_phase_2_flamethrower_scheduler_table";
import AgnaRitualCompletionCheckRow from "./agna_ritual_completion_check_table";
import AgnaSummoningCircleSpawnerRow from "./agna_summoning_circle_spawner_table";
import AgnaTargetSwitchSchedulerRow from "./agna_target_switch_scheduler_table";
import AttackBurstCooldownsRow from "./attack_burst_cooldowns_table";
import AttackDataRow from "./attack_data_table";
import BestiaryRow from "./bestiary_table";
import BossAgnaLastPatternsRow from "./boss_agna_last_patterns_table";
import BossEnderLastPatternsRow from "./boss_ender_last_patterns_table";
import BossPhaseTwoTimerRow from "./boss_phase_two_timer_table";
import BossSelectionRow from "./boss_selection_table";
import BossSimonLastPatternsRow from "./boss_simon_last_patterns_table";
import BossSpawnTimerRow from "./boss_spawn_timer_table";
import BossTargetSwitchSchedulerRow from "./boss_target_switch_scheduler_table";
import ChaosBallSchedulerRow from "./chaos_ball_scheduler_table";
import ChemicalBoltSchedulerRow from "./chemical_bolt_scheduler_table";
import ChosenUpgradesRow from "./chosen_upgrades_table";
import ClassDataRow from "./class_data_table";
import ConfigRow from "./config_table";
import CursesRow from "./curses_table";
import DeadPlayersRow from "./dead_players_table";
import EnderBoltSchedulerRow from "./ender_bolt_scheduler_table";
import EnderClawSpawnerRow from "./ender_claw_spawner_table";
import EnderScytheSchedulerRow from "./ender_scythe_scheduler_table";
import EnderScytheSpawnSchedulerRow from "./ender_scythe_spawn_scheduler_table";
import EntityRow from "./entity_table";
import ExpConfigRow from "./exp_config_table";
import FoundLoreScrollsRow from "./found_lore_scrolls_table";
import GameStateRow from "./game_state_table";
import GemsRow from "./gems_table";
import GuaranteedVoidChestSpawnsRow from "./guaranteed_void_chest_spawns_table";
import HealthRegenTimerRow from "./health_regen_timer_table";
import ImpAttackSchedulerRow from "./imp_attack_scheduler_table";
import LootCapsulesRow from "./loot_capsules_table";
import MonsterDamageRow from "./monster_damage_table";
import MonsterHealthRegenTimerRow from "./monster_health_regen_timer_table";
import MonsterHitCleanupRow from "./monster_hit_cleanup_table";
import MonsterSpawnTimerRow from "./monster_spawn_timer_table";
import MonsterSpawnersRow from "./monster_spawners_table";
import MonsterStateChangesRow from "./monster_state_changes_table";
import MonstersRow from "./monsters_table";
import MonstersBoidRow from "./monsters_boid_table";
import PlayerRow from "./player_table";
import PlayerScheduledAttacksRow from "./player_scheduled_attacks_table";
import SavedAttacksRow from "./saved_attacks_table";
import SavedBuildRow from "./saved_build_table";
import SimonZombieWaveSchedulerRow from "./simon_zombie_wave_scheduler_table";
import ToxicSpraySchedulerRow from "./toxic_spray_scheduler_table";
import ToxicZoneSchedulerRow from "./toxic_zone_scheduler_table";
import UpgradeOptionsRow from "./upgrade_options_table";
import VoidZoneSchedulerRow from "./void_zone_scheduler_table";
import WorldRow from "./world_table";

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
  account: __table({
    name: 'account',
    indexes: [
      { accessor: 'identity', name: 'account_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'account_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, AccountRow),
  active_attack_cleanup: __table({
    name: 'active_attack_cleanup',
    indexes: [
      { accessor: 'active_attack_id', name: 'active_attack_cleanup_active_attack_id_idx_btree', algorithm: 'btree', columns: [
        'activeAttackId',
      ] },
      { accessor: 'scheduled_id', name: 'active_attack_cleanup_scheduled_id_idx_btree', algorithm: 'btree', columns: [
        'scheduledId',
      ] },
    ],
    constraints: [
      { name: 'active_attack_cleanup_scheduled_id_key', constraint: 'unique', columns: ['scheduledId'] },
    ],
  }, ActiveAttackCleanupRow),
  active_attacks: __table({
    name: 'active_attacks',
    indexes: [
      { accessor: 'active_attack_id', name: 'active_attacks_active_attack_id_idx_btree', algorithm: 'btree', columns: [
        'activeAttackId',
      ] },
      { accessor: 'player_id', name: 'active_attacks_player_id_idx_btree', algorithm: 'btree', columns: [
        'playerId',
      ] },
    ],
    constraints: [
      { name: 'active_attacks_active_attack_id_key', constraint: 'unique', columns: ['activeAttackId'] },
    ],
  }, ActiveAttacksRow),
  active_monster_attacks: __table({
    name: 'active_monster_attacks',
    indexes: [
      { accessor: 'active_monster_attack_id', name: 'active_monster_attacks_active_monster_attack_id_idx_btree', algorithm: 'btree', columns: [
        'activeMonsterAttackId',
      ] },
    ],
    constraints: [
      { name: 'active_monster_attacks_active_monster_attack_id_key', constraint: 'unique', columns: ['activeMonsterAttackId'] },
    ],
  }, ActiveMonsterAttacksRow),
  agna_candle_bolt_scheduler: __table({
    name: 'agna_candle_bolt_scheduler',
    indexes: [
      { accessor: 'scheduled_id', name: 'agna_candle_bolt_scheduler_scheduled_id_idx_btree', algorithm: 'btree', columns: [
        'scheduledId',
      ] },
    ],
    constraints: [
      { name: 'agna_candle_bolt_scheduler_scheduled_id_key', constraint: 'unique', columns: ['scheduledId'] },
    ],
  }, AgnaCandleBoltSchedulerRow),
  agna_candle_scheduler: __table({
    name: 'agna_candle_scheduler',
    indexes: [
      { accessor: 'scheduled_id', name: 'agna_candle_scheduler_scheduled_id_idx_btree', algorithm: 'btree', columns: [
        'scheduledId',
      ] },
    ],
    constraints: [
      { name: 'agna_candle_scheduler_scheduled_id_key', constraint: 'unique', columns: ['scheduledId'] },
    ],
  }, AgnaCandleSchedulerRow),
  agna_candle_spawns: __table({
    name: 'agna_candle_spawns',
    indexes: [
      { accessor: 'spawn_id', name: 'agna_candle_spawns_spawn_id_idx_btree', algorithm: 'btree', columns: [
        'spawnId',
      ] },
    ],
    constraints: [
      { name: 'agna_candle_spawns_spawn_id_key', constraint: 'unique', columns: ['spawnId'] },
    ],
  }, AgnaCandleSpawnsRow),
  agna_delayed_orb_scheduler: __table({
    name: 'agna_delayed_orb_scheduler',
    indexes: [
      { accessor: 'scheduled_id', name: 'agna_delayed_orb_scheduler_scheduled_id_idx_btree', algorithm: 'btree', columns: [
        'scheduledId',
      ] },
    ],
    constraints: [
      { name: 'agna_delayed_orb_scheduler_scheduled_id_key', constraint: 'unique', columns: ['scheduledId'] },
    ],
  }, AgnaDelayedOrbSchedulerRow),
  agna_fire_orb_scheduler: __table({
    name: 'agna_fire_orb_scheduler',
    indexes: [
      { accessor: 'scheduled_id', name: 'agna_fire_orb_scheduler_scheduled_id_idx_btree', algorithm: 'btree', columns: [
        'scheduledId',
      ] },
    ],
    constraints: [
      { name: 'agna_fire_orb_scheduler_scheduled_id_key', constraint: 'unique', columns: ['scheduledId'] },
    ],
  }, AgnaFireOrbSchedulerRow),
  agna_flamethrower_scheduler: __table({
    name: 'agna_flamethrower_scheduler',
    indexes: [
      { accessor: 'scheduled_id', name: 'agna_flamethrower_scheduler_scheduled_id_idx_btree', algorithm: 'btree', columns: [
        'scheduledId',
      ] },
    ],
    constraints: [
      { name: 'agna_flamethrower_scheduler_scheduled_id_key', constraint: 'unique', columns: ['scheduledId'] },
    ],
  }, AgnaFlamethrowerSchedulerRow),
  agna_magic_circles: __table({
    name: 'agna_magic_circles',
    indexes: [
      { accessor: 'circle_id', name: 'agna_magic_circles_circle_id_idx_btree', algorithm: 'btree', columns: [
        'circleId',
      ] },
    ],
    constraints: [
      { name: 'agna_magic_circles_circle_id_key', constraint: 'unique', columns: ['circleId'] },
    ],
  }, AgnaMagicCirclesRow),
  agna_phase2_flamethrower_scheduler: __table({
    name: 'agna_phase_2_flamethrower_scheduler',
    indexes: [
      { accessor: 'boss_monster_id', name: 'agna_phase_2_flamethrower_scheduler_boss_monster_id_idx_btree', algorithm: 'btree', columns: [
        'bossMonsterId',
      ] },
      { accessor: 'scheduled_id', name: 'agna_phase_2_flamethrower_scheduler_scheduled_id_idx_btree', algorithm: 'btree', columns: [
        'scheduledId',
      ] },
    ],
    constraints: [
      { name: 'agna_phase_2_flamethrower_scheduler_scheduled_id_key', constraint: 'unique', columns: ['scheduledId'] },
    ],
  }, AgnaPhase2FlamethrowerSchedulerRow),
  agna_ritual_completion_check: __table({
    name: 'agna_ritual_completion_check',
    indexes: [
      { accessor: 'scheduled_id', name: 'agna_ritual_completion_check_scheduled_id_idx_btree', algorithm: 'btree', columns: [
        'scheduledId',
      ] },
    ],
    constraints: [
      { name: 'agna_ritual_completion_check_scheduled_id_key', constraint: 'unique', columns: ['scheduledId'] },
    ],
  }, AgnaRitualCompletionCheckRow),
  agna_summoning_circle_spawner: __table({
    name: 'agna_summoning_circle_spawner',
    indexes: [
      { accessor: 'boss_monster_id', name: 'agna_summoning_circle_spawner_boss_monster_id_idx_btree', algorithm: 'btree', columns: [
        'bossMonsterId',
      ] },
      { accessor: 'scheduled_id', name: 'agna_summoning_circle_spawner_scheduled_id_idx_btree', algorithm: 'btree', columns: [
        'scheduledId',
      ] },
    ],
    constraints: [
      { name: 'agna_summoning_circle_spawner_scheduled_id_key', constraint: 'unique', columns: ['scheduledId'] },
    ],
  }, AgnaSummoningCircleSpawnerRow),
  agna_target_switch_scheduler: __table({
    name: 'agna_target_switch_scheduler',
    indexes: [
      { accessor: 'boss_monster_id', name: 'agna_target_switch_scheduler_boss_monster_id_idx_btree', algorithm: 'btree', columns: [
        'bossMonsterId',
      ] },
      { accessor: 'scheduled_id', name: 'agna_target_switch_scheduler_scheduled_id_idx_btree', algorithm: 'btree', columns: [
        'scheduledId',
      ] },
    ],
    constraints: [
      { name: 'agna_target_switch_scheduler_scheduled_id_key', constraint: 'unique', columns: ['scheduledId'] },
    ],
  }, AgnaTargetSwitchSchedulerRow),
  attack_burst_cooldowns: __table({
    name: 'attack_burst_cooldowns',
    indexes: [
      { accessor: 'player_id', name: 'attack_burst_cooldowns_player_id_idx_btree', algorithm: 'btree', columns: [
        'playerId',
      ] },
      { accessor: 'scheduled_id', name: 'attack_burst_cooldowns_scheduled_id_idx_btree', algorithm: 'btree', columns: [
        'scheduledId',
      ] },
    ],
    constraints: [
      { name: 'attack_burst_cooldowns_scheduled_id_key', constraint: 'unique', columns: ['scheduledId'] },
    ],
  }, AttackBurstCooldownsRow),
  attack_data: __table({
    name: 'attack_data',
    indexes: [
      { accessor: 'attack_id', name: 'attack_data_attack_id_idx_btree', algorithm: 'btree', columns: [
        'attackId',
      ] },
      { accessor: 'attack_type', name: 'attack_data_attack_type_idx_btree', algorithm: 'btree', columns: [
        'attackType',
      ] },
    ],
    constraints: [
      { name: 'attack_data_attack_id_key', constraint: 'unique', columns: ['attackId'] },
      { name: 'attack_data_attack_type_key', constraint: 'unique', columns: ['attackType'] },
    ],
  }, AttackDataRow),
  bestiary: __table({
    name: 'bestiary',
    indexes: [
      { accessor: 'bestiary_id', name: 'bestiary_bestiary_id_idx_btree', algorithm: 'btree', columns: [
        'bestiaryId',
      ] },
    ],
    constraints: [
      { name: 'bestiary_bestiary_id_key', constraint: 'unique', columns: ['bestiaryId'] },
    ],
  }, BestiaryRow),
  boss_agna_last_patterns: __table({
    name: 'boss_agna_last_patterns',
    indexes: [
      { accessor: 'monster_id', name: 'boss_agna_last_patterns_monster_id_idx_btree', algorithm: 'btree', columns: [
        'monsterId',
      ] },
    ],
    constraints: [
      { name: 'boss_agna_last_patterns_monster_id_key', constraint: 'unique', columns: ['monsterId'] },
    ],
  }, BossAgnaLastPatternsRow),
  boss_ender_last_patterns: __table({
    name: 'boss_ender_last_patterns',
    indexes: [
      { accessor: 'monster_id', name: 'boss_ender_last_patterns_monster_id_idx_btree', algorithm: 'btree', columns: [
        'monsterId',
      ] },
    ],
    constraints: [
      { name: 'boss_ender_last_patterns_monster_id_key', constraint: 'unique', columns: ['monsterId'] },
    ],
  }, BossEnderLastPatternsRow),
  boss_phase_two_timer: __table({
    name: 'boss_phase_two_timer',
    indexes: [
      { accessor: 'scheduled_id', name: 'boss_phase_two_timer_scheduled_id_idx_btree', algorithm: 'btree', columns: [
        'scheduledId',
      ] },
    ],
    constraints: [
      { name: 'boss_phase_two_timer_scheduled_id_key', constraint: 'unique', columns: ['scheduledId'] },
    ],
  }, BossPhaseTwoTimerRow),
  boss_selection: __table({
    name: 'boss_selection',
    indexes: [
      { accessor: 'id', name: 'boss_selection_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'boss_selection_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, BossSelectionRow),
  boss_simon_last_patterns: __table({
    name: 'boss_simon_last_patterns',
    indexes: [
      { accessor: 'monster_id', name: 'boss_simon_last_patterns_monster_id_idx_btree', algorithm: 'btree', columns: [
        'monsterId',
      ] },
    ],
    constraints: [
      { name: 'boss_simon_last_patterns_monster_id_key', constraint: 'unique', columns: ['monsterId'] },
    ],
  }, BossSimonLastPatternsRow),
  boss_spawn_timer: __table({
    name: 'boss_spawn_timer',
    indexes: [
      { accessor: 'scheduled_id', name: 'boss_spawn_timer_scheduled_id_idx_btree', algorithm: 'btree', columns: [
        'scheduledId',
      ] },
    ],
    constraints: [
      { name: 'boss_spawn_timer_scheduled_id_key', constraint: 'unique', columns: ['scheduledId'] },
    ],
  }, BossSpawnTimerRow),
  boss_target_switch_scheduler: __table({
    name: 'boss_target_switch_scheduler',
    indexes: [
      { accessor: 'boss_monster_id', name: 'boss_target_switch_scheduler_boss_monster_id_idx_btree', algorithm: 'btree', columns: [
        'bossMonsterId',
      ] },
      { accessor: 'scheduled_id', name: 'boss_target_switch_scheduler_scheduled_id_idx_btree', algorithm: 'btree', columns: [
        'scheduledId',
      ] },
    ],
    constraints: [
      { name: 'boss_target_switch_scheduler_scheduled_id_key', constraint: 'unique', columns: ['scheduledId'] },
    ],
  }, BossTargetSwitchSchedulerRow),
  chaos_ball_scheduler: __table({
    name: 'chaos_ball_scheduler',
    indexes: [
      { accessor: 'boss_monster_id', name: 'chaos_ball_scheduler_boss_monster_id_idx_btree', algorithm: 'btree', columns: [
        'bossMonsterId',
      ] },
      { accessor: 'scheduled_id', name: 'chaos_ball_scheduler_scheduled_id_idx_btree', algorithm: 'btree', columns: [
        'scheduledId',
      ] },
    ],
    constraints: [
      { name: 'chaos_ball_scheduler_scheduled_id_key', constraint: 'unique', columns: ['scheduledId'] },
    ],
  }, ChaosBallSchedulerRow),
  chemical_bolt_scheduler: __table({
    name: 'chemical_bolt_scheduler',
    indexes: [
      { accessor: 'boss_monster_id', name: 'chemical_bolt_scheduler_boss_monster_id_idx_btree', algorithm: 'btree', columns: [
        'bossMonsterId',
      ] },
      { accessor: 'scheduled_id', name: 'chemical_bolt_scheduler_scheduled_id_idx_btree', algorithm: 'btree', columns: [
        'scheduledId',
      ] },
    ],
    constraints: [
      { name: 'chemical_bolt_scheduler_scheduled_id_key', constraint: 'unique', columns: ['scheduledId'] },
    ],
  }, ChemicalBoltSchedulerRow),
  chosen_upgrades: __table({
    name: 'chosen_upgrades',
    indexes: [
      { accessor: 'chosen_upgrade_id', name: 'chosen_upgrades_chosen_upgrade_id_idx_btree', algorithm: 'btree', columns: [
        'chosenUpgradeId',
      ] },
      { accessor: 'player_id', name: 'chosen_upgrades_player_id_idx_btree', algorithm: 'btree', columns: [
        'playerId',
      ] },
    ],
    constraints: [
      { name: 'chosen_upgrades_chosen_upgrade_id_key', constraint: 'unique', columns: ['chosenUpgradeId'] },
    ],
  }, ChosenUpgradesRow),
  class_data: __table({
    name: 'class_data',
    indexes: [
      { accessor: 'class_id', name: 'class_data_class_id_idx_btree', algorithm: 'btree', columns: [
        'classId',
      ] },
    ],
    constraints: [
      { name: 'class_data_class_id_key', constraint: 'unique', columns: ['classId'] },
    ],
  }, ClassDataRow),
  config: __table({
    name: 'config',
    indexes: [
      { accessor: 'id', name: 'config_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'config_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ConfigRow),
  curses: __table({
    name: 'curses',
    indexes: [
      { accessor: 'curse_id', name: 'curses_curse_id_idx_btree', algorithm: 'btree', columns: [
        'curseId',
      ] },
    ],
    constraints: [
      { name: 'curses_curse_id_key', constraint: 'unique', columns: ['curseId'] },
    ],
  }, CursesRow),
  dead_players: __table({
    name: 'dead_players',
    indexes: [
      { accessor: 'player_id', name: 'dead_players_player_id_idx_btree', algorithm: 'btree', columns: [
        'playerId',
      ] },
    ],
    constraints: [
      { name: 'dead_players_player_id_key', constraint: 'unique', columns: ['playerId'] },
    ],
  }, DeadPlayersRow),
  ender_bolt_scheduler: __table({
    name: 'ender_bolt_scheduler',
    indexes: [
      { accessor: 'boss_monster_id', name: 'ender_bolt_scheduler_boss_monster_id_idx_btree', algorithm: 'btree', columns: [
        'bossMonsterId',
      ] },
      { accessor: 'scheduled_id', name: 'ender_bolt_scheduler_scheduled_id_idx_btree', algorithm: 'btree', columns: [
        'scheduledId',
      ] },
    ],
    constraints: [
      { name: 'ender_bolt_scheduler_scheduled_id_key', constraint: 'unique', columns: ['scheduledId'] },
    ],
  }, EnderBoltSchedulerRow),
  ender_claw_spawner: __table({
    name: 'ender_claw_spawner',
    indexes: [
      { accessor: 'boss_monster_id', name: 'ender_claw_spawner_boss_monster_id_idx_btree', algorithm: 'btree', columns: [
        'bossMonsterId',
      ] },
      { accessor: 'scheduled_id', name: 'ender_claw_spawner_scheduled_id_idx_btree', algorithm: 'btree', columns: [
        'scheduledId',
      ] },
    ],
    constraints: [
      { name: 'ender_claw_spawner_scheduled_id_key', constraint: 'unique', columns: ['scheduledId'] },
    ],
  }, EnderClawSpawnerRow),
  ender_scythe_scheduler: __table({
    name: 'ender_scythe_scheduler',
    indexes: [
      { accessor: 'boss_monster_id', name: 'ender_scythe_scheduler_boss_monster_id_idx_btree', algorithm: 'btree', columns: [
        'bossMonsterId',
      ] },
      { accessor: 'scheduled_id', name: 'ender_scythe_scheduler_scheduled_id_idx_btree', algorithm: 'btree', columns: [
        'scheduledId',
      ] },
    ],
    constraints: [
      { name: 'ender_scythe_scheduler_scheduled_id_key', constraint: 'unique', columns: ['scheduledId'] },
    ],
  }, EnderScytheSchedulerRow),
  ender_scythe_spawn_scheduler: __table({
    name: 'ender_scythe_spawn_scheduler',
    indexes: [
      { accessor: 'boss_monster_id', name: 'ender_scythe_spawn_scheduler_boss_monster_id_idx_btree', algorithm: 'btree', columns: [
        'bossMonsterId',
      ] },
      { accessor: 'scheduled_id', name: 'ender_scythe_spawn_scheduler_scheduled_id_idx_btree', algorithm: 'btree', columns: [
        'scheduledId',
      ] },
    ],
    constraints: [
      { name: 'ender_scythe_spawn_scheduler_scheduled_id_key', constraint: 'unique', columns: ['scheduledId'] },
    ],
  }, EnderScytheSpawnSchedulerRow),
  entity: __table({
    name: 'entity',
    indexes: [
      { accessor: 'entity_id', name: 'entity_entity_id_idx_btree', algorithm: 'btree', columns: [
        'entityId',
      ] },
    ],
    constraints: [
      { name: 'entity_entity_id_key', constraint: 'unique', columns: ['entityId'] },
    ],
  }, EntityRow),
  exp_config: __table({
    name: 'exp_config',
    indexes: [
      { accessor: 'config_id', name: 'exp_config_config_id_idx_btree', algorithm: 'btree', columns: [
        'configId',
      ] },
    ],
    constraints: [
      { name: 'exp_config_config_id_key', constraint: 'unique', columns: ['configId'] },
    ],
  }, ExpConfigRow),
  found_lore_scrolls: __table({
    name: 'found_lore_scrolls',
    indexes: [
      { accessor: 'pickup_id', name: 'found_lore_scrolls_pickup_id_idx_btree', algorithm: 'btree', columns: [
        'pickupId',
      ] },
    ],
    constraints: [
      { name: 'found_lore_scrolls_pickup_id_key', constraint: 'unique', columns: ['pickupId'] },
    ],
  }, FoundLoreScrollsRow),
  game_state: __table({
    name: 'game_state',
    indexes: [
      { accessor: 'id', name: 'game_state_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'game_state_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, GameStateRow),
  gems: __table({
    name: 'gems',
    indexes: [
      { accessor: 'entity_id', name: 'gems_entity_id_idx_btree', algorithm: 'btree', columns: [
        'entityId',
      ] },
      { accessor: 'gem_id', name: 'gems_gem_id_idx_btree', algorithm: 'btree', columns: [
        'gemId',
      ] },
    ],
    constraints: [
      { name: 'gems_entity_id_key', constraint: 'unique', columns: ['entityId'] },
      { name: 'gems_gem_id_key', constraint: 'unique', columns: ['gemId'] },
    ],
  }, GemsRow),
  guaranteed_void_chest_spawns: __table({
    name: 'guaranteed_void_chest_spawns',
    indexes: [
      { accessor: 'scheduled_id', name: 'guaranteed_void_chest_spawns_scheduled_id_idx_btree', algorithm: 'btree', columns: [
        'scheduledId',
      ] },
    ],
    constraints: [
      { name: 'guaranteed_void_chest_spawns_scheduled_id_key', constraint: 'unique', columns: ['scheduledId'] },
    ],
  }, GuaranteedVoidChestSpawnsRow),
  health_regen_timer: __table({
    name: 'health_regen_timer',
    indexes: [
      { accessor: 'scheduled_id', name: 'health_regen_timer_scheduled_id_idx_btree', algorithm: 'btree', columns: [
        'scheduledId',
      ] },
    ],
    constraints: [
      { name: 'health_regen_timer_scheduled_id_key', constraint: 'unique', columns: ['scheduledId'] },
    ],
  }, HealthRegenTimerRow),
  imp_attack_scheduler: __table({
    name: 'imp_attack_scheduler',
    indexes: [
      { accessor: 'imp_monster_id', name: 'imp_attack_scheduler_imp_monster_id_idx_btree', algorithm: 'btree', columns: [
        'impMonsterId',
      ] },
      { accessor: 'scheduled_id', name: 'imp_attack_scheduler_scheduled_id_idx_btree', algorithm: 'btree', columns: [
        'scheduledId',
      ] },
    ],
    constraints: [
      { name: 'imp_attack_scheduler_scheduled_id_key', constraint: 'unique', columns: ['scheduledId'] },
    ],
  }, ImpAttackSchedulerRow),
  loot_capsules: __table({
    name: 'loot_capsules',
    indexes: [
      { accessor: 'capsule_id', name: 'loot_capsules_capsule_id_idx_btree', algorithm: 'btree', columns: [
        'capsuleId',
      ] },
    ],
    constraints: [
      { name: 'loot_capsules_capsule_id_key', constraint: 'unique', columns: ['capsuleId'] },
    ],
  }, LootCapsulesRow),
  monster_damage: __table({
    name: 'monster_damage',
    indexes: [
      { accessor: 'attack_entity_id', name: 'monster_damage_attack_entity_id_idx_btree', algorithm: 'btree', columns: [
        'attackEntityId',
      ] },
      { accessor: 'damage_id', name: 'monster_damage_damage_id_idx_btree', algorithm: 'btree', columns: [
        'damageId',
      ] },
      { accessor: 'monster_id', name: 'monster_damage_monster_id_idx_btree', algorithm: 'btree', columns: [
        'monsterId',
      ] },
    ],
    constraints: [
      { name: 'monster_damage_damage_id_key', constraint: 'unique', columns: ['damageId'] },
    ],
  }, MonsterDamageRow),
  monster_health_regen_timer: __table({
    name: 'monster_health_regen_timer',
    indexes: [
      { accessor: 'scheduled_id', name: 'monster_health_regen_timer_scheduled_id_idx_btree', algorithm: 'btree', columns: [
        'scheduledId',
      ] },
    ],
    constraints: [
      { name: 'monster_health_regen_timer_scheduled_id_key', constraint: 'unique', columns: ['scheduledId'] },
    ],
  }, MonsterHealthRegenTimerRow),
  monster_hit_cleanup: __table({
    name: 'monster_hit_cleanup',
    indexes: [
      { accessor: 'scheduled_id', name: 'monster_hit_cleanup_scheduled_id_idx_btree', algorithm: 'btree', columns: [
        'scheduledId',
      ] },
    ],
    constraints: [
      { name: 'monster_hit_cleanup_scheduled_id_key', constraint: 'unique', columns: ['scheduledId'] },
    ],
  }, MonsterHitCleanupRow),
  monster_spawn_timer: __table({
    name: 'monster_spawn_timer',
    indexes: [
      { accessor: 'scheduled_id', name: 'monster_spawn_timer_scheduled_id_idx_btree', algorithm: 'btree', columns: [
        'scheduledId',
      ] },
    ],
    constraints: [
      { name: 'monster_spawn_timer_scheduled_id_key', constraint: 'unique', columns: ['scheduledId'] },
    ],
  }, MonsterSpawnTimerRow),
  monster_spawners: __table({
    name: 'monster_spawners',
    indexes: [
      { accessor: 'scheduled_id', name: 'monster_spawners_scheduled_id_idx_btree', algorithm: 'btree', columns: [
        'scheduledId',
      ] },
    ],
    constraints: [
      { name: 'monster_spawners_scheduled_id_key', constraint: 'unique', columns: ['scheduledId'] },
    ],
  }, MonsterSpawnersRow),
  monster_state_changes: __table({
    name: 'monster_state_changes',
    indexes: [
      { accessor: 'scheduled_id', name: 'monster_state_changes_scheduled_id_idx_btree', algorithm: 'btree', columns: [
        'scheduledId',
      ] },
    ],
    constraints: [
      { name: 'monster_state_changes_scheduled_id_key', constraint: 'unique', columns: ['scheduledId'] },
    ],
  }, MonsterStateChangesRow),
  monsters: __table({
    name: 'monsters',
    indexes: [
      { accessor: 'monster_id', name: 'monsters_monster_id_idx_btree', algorithm: 'btree', columns: [
        'monsterId',
      ] },
    ],
    constraints: [
      { name: 'monsters_monster_id_key', constraint: 'unique', columns: ['monsterId'] },
    ],
  }, MonstersRow),
  monsters_boid: __table({
    name: 'monsters_boid',
    indexes: [
      { accessor: 'monster_id', name: 'monsters_boid_monster_id_idx_btree', algorithm: 'btree', columns: [
        'monsterId',
      ] },
    ],
    constraints: [
      { name: 'monsters_boid_monster_id_key', constraint: 'unique', columns: ['monsterId'] },
    ],
  }, MonstersBoidRow),
  player: __table({
    name: 'player',
    indexes: [
      { accessor: 'player_id', name: 'player_player_id_idx_btree', algorithm: 'btree', columns: [
        'playerId',
      ] },
    ],
    constraints: [
      { name: 'player_player_id_key', constraint: 'unique', columns: ['playerId'] },
    ],
  }, PlayerRow),
  player_scheduled_attacks: __table({
    name: 'player_scheduled_attacks',
    indexes: [
      { accessor: 'player_id', name: 'player_scheduled_attacks_player_id_idx_btree', algorithm: 'btree', columns: [
        'playerId',
      ] },
      { accessor: 'scheduled_id', name: 'player_scheduled_attacks_scheduled_id_idx_btree', algorithm: 'btree', columns: [
        'scheduledId',
      ] },
    ],
    constraints: [
      { name: 'player_scheduled_attacks_scheduled_id_key', constraint: 'unique', columns: ['scheduledId'] },
    ],
  }, PlayerScheduledAttacksRow),
  saved_attacks: __table({
    name: 'saved_attacks',
    indexes: [
      { accessor: 'saved_attack_id', name: 'saved_attacks_saved_attack_id_idx_btree', algorithm: 'btree', columns: [
        'savedAttackId',
      ] },
    ],
    constraints: [
      { name: 'saved_attacks_saved_attack_id_key', constraint: 'unique', columns: ['savedAttackId'] },
    ],
  }, SavedAttacksRow),
  saved_build: __table({
    name: 'saved_build',
    indexes: [
      { accessor: 'build_id', name: 'saved_build_build_id_idx_btree', algorithm: 'btree', columns: [
        'buildId',
      ] },
    ],
    constraints: [
      { name: 'saved_build_build_id_key', constraint: 'unique', columns: ['buildId'] },
    ],
  }, SavedBuildRow),
  simon_zombie_wave_scheduler: __table({
    name: 'simon_zombie_wave_scheduler',
    indexes: [
      { accessor: 'boss_monster_id', name: 'simon_zombie_wave_scheduler_boss_monster_id_idx_btree', algorithm: 'btree', columns: [
        'bossMonsterId',
      ] },
      { accessor: 'scheduled_id', name: 'simon_zombie_wave_scheduler_scheduled_id_idx_btree', algorithm: 'btree', columns: [
        'scheduledId',
      ] },
    ],
    constraints: [
      { name: 'simon_zombie_wave_scheduler_scheduled_id_key', constraint: 'unique', columns: ['scheduledId'] },
    ],
  }, SimonZombieWaveSchedulerRow),
  toxic_spray_scheduler: __table({
    name: 'toxic_spray_scheduler',
    indexes: [
      { accessor: 'boss_monster_id', name: 'toxic_spray_scheduler_boss_monster_id_idx_btree', algorithm: 'btree', columns: [
        'bossMonsterId',
      ] },
      { accessor: 'scheduled_id', name: 'toxic_spray_scheduler_scheduled_id_idx_btree', algorithm: 'btree', columns: [
        'scheduledId',
      ] },
    ],
    constraints: [
      { name: 'toxic_spray_scheduler_scheduled_id_key', constraint: 'unique', columns: ['scheduledId'] },
    ],
  }, ToxicSpraySchedulerRow),
  toxic_zone_scheduler: __table({
    name: 'toxic_zone_scheduler',
    indexes: [
      { accessor: 'boss_monster_id', name: 'toxic_zone_scheduler_boss_monster_id_idx_btree', algorithm: 'btree', columns: [
        'bossMonsterId',
      ] },
      { accessor: 'scheduled_id', name: 'toxic_zone_scheduler_scheduled_id_idx_btree', algorithm: 'btree', columns: [
        'scheduledId',
      ] },
    ],
    constraints: [
      { name: 'toxic_zone_scheduler_scheduled_id_key', constraint: 'unique', columns: ['scheduledId'] },
    ],
  }, ToxicZoneSchedulerRow),
  upgrade_options: __table({
    name: 'upgrade_options',
    indexes: [
      { accessor: 'player_id', name: 'upgrade_options_player_id_idx_btree', algorithm: 'btree', columns: [
        'playerId',
      ] },
      { accessor: 'upgrade_id', name: 'upgrade_options_upgrade_id_idx_btree', algorithm: 'btree', columns: [
        'upgradeId',
      ] },
    ],
    constraints: [
      { name: 'upgrade_options_upgrade_id_key', constraint: 'unique', columns: ['upgradeId'] },
    ],
  }, UpgradeOptionsRow),
  void_zone_scheduler: __table({
    name: 'void_zone_scheduler',
    indexes: [
      { accessor: 'boss_monster_id', name: 'void_zone_scheduler_boss_monster_id_idx_btree', algorithm: 'btree', columns: [
        'bossMonsterId',
      ] },
      { accessor: 'scheduled_id', name: 'void_zone_scheduler_scheduled_id_idx_btree', algorithm: 'btree', columns: [
        'scheduledId',
      ] },
    ],
    constraints: [
      { name: 'void_zone_scheduler_scheduled_id_key', constraint: 'unique', columns: ['scheduledId'] },
    ],
  }, VoidZoneSchedulerRow),
  world: __table({
    name: 'world',
    indexes: [
      { accessor: 'world_id', name: 'world_world_id_idx_btree', algorithm: 'btree', columns: [
        'worldId',
      ] },
    ],
    constraints: [
      { name: 'world_world_id_key', constraint: 'unique', columns: ['worldId'] },
    ],
  }, WorldRow),
});

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("admin_add_curse", AdminAddCurseReducer),
  __reducerSchema("admin_add_debug_curse", AdminAddDebugCurseReducer),
  __reducerSchema("admin_clear_curses", AdminClearCursesReducer),
  __reducerSchema("choose_upgrade", ChooseUpgradeReducer),
  __reducerSchema("cleanup_game_state", CleanupGameStateReducer),
  __reducerSchema("debug_check_gem_drops", DebugCheckGemDropsReducer),
  __reducerSchema("debug_check_tier", DebugCheckTierReducer),
  __reducerSchema("debug_enable_bot_pvp", DebugEnableBotPvpReducer),
  __reducerSchema("debug_set_boss_type", DebugSetBossTypeReducer),
  __reducerSchema("debug_set_super_health", DebugSetSuperHealthReducer),
  __reducerSchema("init_attack_data", InitAttackDataReducer),
  __reducerSchema("init_health_regen_system", InitHealthRegenSystemReducer),
  __reducerSchema("load_build", LoadBuildReducer),
  __reducerSchema("reroll_upgrades", RerollUpgradesReducer),
  __reducerSchema("reset_world", ResetWorldReducer),
  __reducerSchema("save_build", SaveBuildReducer),
  __reducerSchema("set_name", SetNameReducer),
  __reducerSchema("set_player_pvp_mode", SetPlayerPvpModeReducer),
  __reducerSchema("set_player_waypoint", SetPlayerWaypointReducer),
  __reducerSchema("spawn_boss_for_testing", SpawnBossForTestingReducer),
  __reducerSchema("spawn_bot", SpawnBotReducer),
  __reducerSchema("spawn_debug_loot_capsule", SpawnDebugLootCapsuleReducer),
  __reducerSchema("spawn_debug_lore_scroll", SpawnDebugLoreScrollReducer),
  __reducerSchema("spawn_debug_special_gem", SpawnDebugSpecialGemReducer),
  __reducerSchema("spawn_debug_void_chest", SpawnDebugVoidChestReducer),
  __reducerSchema("spawn_player", SpawnPlayerReducer),
  __reducerSchema("update_last_login", UpdateLastLoginReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
);

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.1.0" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
export const tables: __QueryBuilder<typeof tablesSchema.schemaType> = __makeQueryBuilder(tablesSchema.schemaType);

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The context type returned in callbacks for all possible events. */
export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = __ReducerEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = __SubscriptionEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for error events. */
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

