// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  DbVector2,
  GemLevel,
} from "./types";


export default __t.row({
  capsuleId: __t.u64().primaryKey().name("capsule_id"),
  get startPosition() {
    return DbVector2.name("start_position");
  },
  get endPosition() {
    return DbVector2.name("end_position");
  },
  get lootdropId() {
    return GemLevel.name("lootdrop_id");
  },
  scheduledAt: __t.scheduleAt().name("scheduled_at"),
});
