// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  DbVector2,
  MonsterType,
  AiState,
  MonsterVariant,
} from "./types";


export default __t.row({
  monsterId: __t.u32().primaryKey().name("monster_id"),
  get bestiaryId() {
    return MonsterType.name("bestiary_id");
  },
  get variant() {
    return MonsterVariant;
  },
  hp: __t.u32(),
  maxHp: __t.u32().name("max_hp"),
  atk: __t.f32(),
  speed: __t.f32(),
  targetPlayerId: __t.u32().name("target_player_id"),
  get aiState() {
    return AiState.name("ai_state");
  },
  radius: __t.f32(),
  get spawnPosition() {
    return DbVector2.name("spawn_position");
  },
});
