// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
} from "spacetimedb";
import { DbVector2 } from "./db_vector_2_type";
// Mark import as potentially unused
declare type __keep_DbVector2 = DbVector2;
import { MonsterType } from "./monster_type_type";
// Mark import as potentially unused
declare type __keep_MonsterType = MonsterType;


export type MonsterSpawners = {
  scheduledId: bigint,
  position: DbVector2,
  monsterType: MonsterType,
  scheduledAt: { tag: "Interval", value: __TimeDuration } | { tag: "Time", value: __Timestamp },
};
/**
 * An object for generated helper functions.
 */
export const MonsterSpawners = {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    return __AlgebraicTypeValue.Product({
      elements: [
        { name: "scheduledId", algebraicType: __AlgebraicTypeValue.U64},
        { name: "position", algebraicType: DbVector2.getTypeScriptAlgebraicType()},
        { name: "monsterType", algebraicType: MonsterType.getTypeScriptAlgebraicType()},
        { name: "scheduledAt", algebraicType: __AlgebraicTypeValue.createScheduleAtType()},
      ]
    });
  },

  serialize(writer: __BinaryWriter, value: MonsterSpawners): void {
    __AlgebraicTypeValue.serializeValue(writer, MonsterSpawners.getTypeScriptAlgebraicType(), value);
  },

  deserialize(reader: __BinaryReader): MonsterSpawners {
    return __AlgebraicTypeValue.deserializeValue(reader, MonsterSpawners.getTypeScriptAlgebraicType());
  },

}

export default MonsterSpawners;


