// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
// A namespace for generated variants and helper functions.
export namespace MonsterAttackType {
  // These are the generated variant types for each variant of the tagged union.
  // One type is generated per variant and will be used in the `value` field of
  // the tagged union.
  export type ImpBolt = { tag: "ImpBolt" };
  export type EnderBolt = { tag: "EnderBolt" };
  export type EnderScytheSpawn = { tag: "EnderScytheSpawn" };
  export type EnderScythe = { tag: "EnderScythe" };
  export type ChaosBall = { tag: "ChaosBall" };
  export type VoidZone = { tag: "VoidZone" };
  export type AgnaFlamethrowerJet = { tag: "AgnaFlamethrowerJet" };
  export type AgnaOrbSpawn = { tag: "AgnaOrbSpawn" };
  export type AgnaFireOrb = { tag: "AgnaFireOrb" };
  export type AgnaCandleBolt = { tag: "AgnaCandleBolt" };
  export type AgnaPhase2FlameJet = { tag: "AgnaPhase2FlameJet" };
  export type AgnaGroundFlame = { tag: "AgnaGroundFlame" };
  export type SimonChemicalBolt = { tag: "SimonChemicalBolt" };
  export type SimonToxicZone = { tag: "SimonToxicZone" };
  export type SimonToxicSpray = { tag: "SimonToxicSpray" };

  // Helper functions for constructing each variant of the tagged union.
  // ```
  // const foo = Foo.A(42);
  // assert!(foo.tag === "A");
  // assert!(foo.value === 42);
  // ```
  export const ImpBolt = { tag: "ImpBolt" };
  export const EnderBolt = { tag: "EnderBolt" };
  export const EnderScytheSpawn = { tag: "EnderScytheSpawn" };
  export const EnderScythe = { tag: "EnderScythe" };
  export const ChaosBall = { tag: "ChaosBall" };
  export const VoidZone = { tag: "VoidZone" };
  export const AgnaFlamethrowerJet = { tag: "AgnaFlamethrowerJet" };
  export const AgnaOrbSpawn = { tag: "AgnaOrbSpawn" };
  export const AgnaFireOrb = { tag: "AgnaFireOrb" };
  export const AgnaCandleBolt = { tag: "AgnaCandleBolt" };
  export const AgnaPhase2FlameJet = { tag: "AgnaPhase2FlameJet" };
  export const AgnaGroundFlame = { tag: "AgnaGroundFlame" };
  export const SimonChemicalBolt = { tag: "SimonChemicalBolt" };
  export const SimonToxicZone = { tag: "SimonToxicZone" };
  export const SimonToxicSpray = { tag: "SimonToxicSpray" };

  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createSumType([
      new SumTypeVariant("ImpBolt", AlgebraicType.createProductType([])),
      new SumTypeVariant("EnderBolt", AlgebraicType.createProductType([])),
      new SumTypeVariant("EnderScytheSpawn", AlgebraicType.createProductType([])),
      new SumTypeVariant("EnderScythe", AlgebraicType.createProductType([])),
      new SumTypeVariant("ChaosBall", AlgebraicType.createProductType([])),
      new SumTypeVariant("VoidZone", AlgebraicType.createProductType([])),
      new SumTypeVariant("AgnaFlamethrowerJet", AlgebraicType.createProductType([])),
      new SumTypeVariant("AgnaOrbSpawn", AlgebraicType.createProductType([])),
      new SumTypeVariant("AgnaFireOrb", AlgebraicType.createProductType([])),
      new SumTypeVariant("AgnaCandleBolt", AlgebraicType.createProductType([])),
      new SumTypeVariant("AgnaPhase2FlameJet", AlgebraicType.createProductType([])),
      new SumTypeVariant("AgnaGroundFlame", AlgebraicType.createProductType([])),
      new SumTypeVariant("SimonChemicalBolt", AlgebraicType.createProductType([])),
      new SumTypeVariant("SimonToxicZone", AlgebraicType.createProductType([])),
      new SumTypeVariant("SimonToxicSpray", AlgebraicType.createProductType([])),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: MonsterAttackType): void {
      MonsterAttackType.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): MonsterAttackType {
      return MonsterAttackType.getTypeScriptAlgebraicType().deserialize(reader);
  }

}

// The tagged union or sum type for the algebraic type `MonsterAttackType`.
export type MonsterAttackType = MonsterAttackType.ImpBolt | MonsterAttackType.EnderBolt | MonsterAttackType.EnderScytheSpawn | MonsterAttackType.EnderScythe | MonsterAttackType.ChaosBall | MonsterAttackType.VoidZone | MonsterAttackType.AgnaFlamethrowerJet | MonsterAttackType.AgnaOrbSpawn | MonsterAttackType.AgnaFireOrb | MonsterAttackType.AgnaCandleBolt | MonsterAttackType.AgnaPhase2FlameJet | MonsterAttackType.AgnaGroundFlame | MonsterAttackType.SimonChemicalBolt | MonsterAttackType.SimonToxicZone | MonsterAttackType.SimonToxicSpray;

export default MonsterAttackType;

