// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
} from "spacetimedb";

export type Rat = { tag: "Rat" };
export type Slime = { tag: "Slime" };
export type Bat = { tag: "Bat" };
export type Orc = { tag: "Orc" };
export type Imp = { tag: "Imp" };
export type Zombie = { tag: "Zombie" };
export type VoidChest = { tag: "VoidChest" };
export type EnderClaw = { tag: "EnderClaw" };
export type BossEnderPhase1 = { tag: "BossEnderPhase1" };
export type BossEnderPhase2 = { tag: "BossEnderPhase2" };
export type BossAgnaPhase1 = { tag: "BossAgnaPhase1" };
export type BossAgnaPhase2 = { tag: "BossAgnaPhase2" };
export type BossSimonPhase1 = { tag: "BossSimonPhase1" };
export type BossSimonPhase2 = { tag: "BossSimonPhase2" };
export type AgnaCandle = { tag: "AgnaCandle" };
export type Crate = { tag: "Crate" };
export type Tree = { tag: "Tree" };
export type Statue = { tag: "Statue" };

