// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
} from "spacetimedb";
import * as MonsterTypeVariants from './monster_type_variants'

// The tagged union or sum type for the algebraic type `MonsterType`.
export type MonsterType = MonsterTypeVariants.Rat |
  MonsterTypeVariants.Slime |
  MonsterTypeVariants.Bat |
  MonsterTypeVariants.Orc |
  MonsterTypeVariants.Imp |
  MonsterTypeVariants.Zombie |
  MonsterTypeVariants.VoidChest |
  MonsterTypeVariants.EnderClaw |
  MonsterTypeVariants.BossEnderPhase1 |
  MonsterTypeVariants.BossEnderPhase2 |
  MonsterTypeVariants.BossAgnaPhase1 |
  MonsterTypeVariants.BossAgnaPhase2 |
  MonsterTypeVariants.BossSimonPhase1 |
  MonsterTypeVariants.BossSimonPhase2 |
  MonsterTypeVariants.AgnaCandle |
  MonsterTypeVariants.Crate |
  MonsterTypeVariants.Tree |
  MonsterTypeVariants.Statue;

// A value with helper functions to construct the type.
export const MonsterType = {
  // Helper functions for constructing each variant of the tagged union.
  // ```
  // const foo = Foo.A(42);
  // assert!(foo.tag === "A");
  // assert!(foo.value === 42);
  // ```
  Rat: { tag: "Rat" } as const,
  Slime: { tag: "Slime" } as const,
  Bat: { tag: "Bat" } as const,
  Orc: { tag: "Orc" } as const,
  Imp: { tag: "Imp" } as const,
  Zombie: { tag: "Zombie" } as const,
  VoidChest: { tag: "VoidChest" } as const,
  EnderClaw: { tag: "EnderClaw" } as const,
  BossEnderPhase1: { tag: "BossEnderPhase1" } as const,
  BossEnderPhase2: { tag: "BossEnderPhase2" } as const,
  BossAgnaPhase1: { tag: "BossAgnaPhase1" } as const,
  BossAgnaPhase2: { tag: "BossAgnaPhase2" } as const,
  BossSimonPhase1: { tag: "BossSimonPhase1" } as const,
  BossSimonPhase2: { tag: "BossSimonPhase2" } as const,
  AgnaCandle: { tag: "AgnaCandle" } as const,
  Crate: { tag: "Crate" } as const,
  Tree: { tag: "Tree" } as const,
  Statue: { tag: "Statue" } as const,

  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    return __AlgebraicTypeValue.Sum({
      variants: [
        { name: "Rat", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "Slime", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "Bat", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "Orc", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "Imp", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "Zombie", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "VoidChest", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "EnderClaw", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "BossEnderPhase1", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "BossEnderPhase2", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "BossAgnaPhase1", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "BossAgnaPhase2", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "BossSimonPhase1", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "BossSimonPhase2", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "AgnaCandle", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "Crate", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "Tree", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "Statue", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
      ]
    });
  },

  serialize(writer: __BinaryWriter, value: MonsterType): void {
      __AlgebraicTypeValue.serializeValue(writer, MonsterType.getTypeScriptAlgebraicType(), value);
  },

  deserialize(reader: __BinaryReader): MonsterType {
      return __AlgebraicTypeValue.deserializeValue(reader, MonsterType.getTypeScriptAlgebraicType());
  },

}

export default MonsterType;


