// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
import { DbVector2 as __DbVector2 } from "./db_vector_2_type";
import { MonsterType as __MonsterType } from "./monster_type_type";
import { AiState as __AiState } from "./ai_state_type";
import { MonsterVariant as __MonsterVariant } from "./monster_variant_type";

export type Monsters = {
  monsterId: number,
  bestiaryId: __MonsterType,
  variant: __MonsterVariant,
  hp: number,
  maxHp: number,
  atk: number,
  speed: number,
  targetPlayerId: number,
  aiState: __AiState,
  radius: number,
  spawnPosition: __DbVector2,
};

/**
 * A namespace for generated helper functions.
 */
export namespace Monsters {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("monsterId", AlgebraicType.createU32Type()),
      new ProductTypeElement("bestiaryId", __MonsterType.getTypeScriptAlgebraicType()),
      new ProductTypeElement("variant", __MonsterVariant.getTypeScriptAlgebraicType()),
      new ProductTypeElement("hp", AlgebraicType.createU32Type()),
      new ProductTypeElement("maxHp", AlgebraicType.createU32Type()),
      new ProductTypeElement("atk", AlgebraicType.createF32Type()),
      new ProductTypeElement("speed", AlgebraicType.createF32Type()),
      new ProductTypeElement("targetPlayerId", AlgebraicType.createU32Type()),
      new ProductTypeElement("aiState", __AiState.getTypeScriptAlgebraicType()),
      new ProductTypeElement("radius", AlgebraicType.createF32Type()),
      new ProductTypeElement("spawnPosition", __DbVector2.getTypeScriptAlgebraicType()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: Monsters): void {
    Monsters.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): Monsters {
    return Monsters.getTypeScriptAlgebraicType().deserialize(reader);
  }

}


