// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
import { Monsters } from "./monsters_type";
import { DbVector2 as __DbVector2 } from "./db_vector_2_type";
import { MonsterType as __MonsterType } from "./monster_type_type";
import { AiState as __AiState } from "./ai_state_type";
import { MonsterVariant as __MonsterVariant } from "./monster_variant_type";

import { type EventContext, type Reducer, RemoteReducers, RemoteTables } from ".";

/**
 * Table handle for the table `monsters`.
 *
 * Obtain a handle from the [`monsters`] property on [`RemoteTables`],
 * like `ctx.db.monsters`.
 *
 * Users are encouraged not to explicitly reference this type,
 * but to directly chain method calls,
 * like `ctx.db.monsters.on_insert(...)`.
 */
export class MonstersTableHandle {
  tableCache: TableCache<Monsters>;

  constructor(tableCache: TableCache<Monsters>) {
    this.tableCache = tableCache;
  }

  count(): number {
    return this.tableCache.count();
  }

  iter(): Iterable<Monsters> {
    return this.tableCache.iter();
  }
  /**
   * Access to the `monsterId` unique index on the table `monsters`,
   * which allows point queries on the field of the same name
   * via the [`MonstersMonsterIdUnique.find`] method.
   *
   * Users are encouraged not to explicitly reference this type,
   * but to directly chain method calls,
   * like `ctx.db.monsters.monsterId().find(...)`.
   *
   * Get a handle on the `monsterId` unique index on the table `monsters`.
   */
  monsterId = {
    // Find the subscribed row whose `monsterId` column value is equal to `col_val`,
    // if such a row is present in the client cache.
    find: (col_val: number): Monsters | undefined => {
      for (let row of this.tableCache.iter()) {
        if (deepEqual(row.monsterId, col_val)) {
          return row;
        }
      }
    },
  };

  onInsert = (cb: (ctx: EventContext, row: Monsters) => void) => {
    return this.tableCache.onInsert(cb);
  }

  removeOnInsert = (cb: (ctx: EventContext, row: Monsters) => void) => {
    return this.tableCache.removeOnInsert(cb);
  }

  onDelete = (cb: (ctx: EventContext, row: Monsters) => void) => {
    return this.tableCache.onDelete(cb);
  }

  removeOnDelete = (cb: (ctx: EventContext, row: Monsters) => void) => {
    return this.tableCache.removeOnDelete(cb);
  }

  // Updates are only defined for tables with primary keys.
  onUpdate = (cb: (ctx: EventContext, oldRow: Monsters, newRow: Monsters) => void) => {
    return this.tableCache.onUpdate(cb);
  }

  removeOnUpdate = (cb: (ctx: EventContext, onRow: Monsters, newRow: Monsters) => void) => {
    return this.tableCache.removeOnUpdate(cb);
  }}
