// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  CallReducerFlags,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  DbContext,
  ErrorContextInterface,
  Event,
  EventContextInterface,
  Identity,
  ProductType,
  ProductTypeElement,
  ReducerEventContextInterface,
  SubscriptionBuilderImpl,
  SubscriptionEventContextInterface,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
} from "@clockworklabs/spacetimedb-sdk";
import { MonsterDamage } from "./monster_damage_type";
import { EventContext, Reducer, RemoteReducers, RemoteTables } from ".";

/**
 * Table handle for the table `monster_damage`.
 *
 * Obtain a handle from the [`monsterDamage`] property on [`RemoteTables`],
 * like `ctx.db.monsterDamage`.
 *
 * Users are encouraged not to explicitly reference this type,
 * but to directly chain method calls,
 * like `ctx.db.monsterDamage.on_insert(...)`.
 */
export class MonsterDamageTableHandle {
  tableCache: TableCache<MonsterDamage>;

  constructor(tableCache: TableCache<MonsterDamage>) {
    this.tableCache = tableCache;
  }

  count(): number {
    return this.tableCache.count();
  }

  iter(): Iterable<MonsterDamage> {
    return this.tableCache.iter();
  }
  /**
   * Access to the `damageId` unique index on the table `monster_damage`,
   * which allows point queries on the field of the same name
   * via the [`MonsterDamageDamageIdUnique.find`] method.
   *
   * Users are encouraged not to explicitly reference this type,
   * but to directly chain method calls,
   * like `ctx.db.monsterDamage.damageId().find(...)`.
   *
   * Get a handle on the `damageId` unique index on the table `monster_damage`.
   */
  damageId = {
    // Find the subscribed row whose `damageId` column value is equal to `col_val`,
    // if such a row is present in the client cache.
    find: (col_val: number): MonsterDamage | undefined => {
      for (let row of this.tableCache.iter()) {
        if (deepEqual(row.damageId, col_val)) {
          return row;
        }
      }
    },
  };

  onInsert = (cb: (ctx: EventContext, row: MonsterDamage) => void) => {
    return this.tableCache.onInsert(cb);
  }

  removeOnInsert = (cb: (ctx: EventContext, row: MonsterDamage) => void) => {
    return this.tableCache.removeOnInsert(cb);
  }

  onDelete = (cb: (ctx: EventContext, row: MonsterDamage) => void) => {
    return this.tableCache.onDelete(cb);
  }

  removeOnDelete = (cb: (ctx: EventContext, row: MonsterDamage) => void) => {
    return this.tableCache.removeOnDelete(cb);
  }

  // Updates are only defined for tables with primary keys.
  onUpdate = (cb: (ctx: EventContext, oldRow: MonsterDamage, newRow: MonsterDamage) => void) => {
    return this.tableCache.onUpdate(cb);
  }

  removeOnUpdate = (cb: (ctx: EventContext, onRow: MonsterDamage, newRow: MonsterDamage) => void) => {
    return this.tableCache.removeOnUpdate(cb);
  }}
