// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  DbVector2,
  MonsterType,
} from "./types";


export default __t.row({
  scheduledId: __t.u64().primaryKey().name("scheduled_id"),
  get position() {
    return DbVector2;
  },
  get monsterType() {
    return MonsterType.name("monster_type");
  },
  scheduledAt: __t.scheduleAt().name("scheduled_at"),
});
