// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
} from "spacetimedb";
import { DbVector2 } from "./db_vector_2_type";
// Mark import as potentially unused
declare type __keep_DbVector2 = DbVector2;
import { PlayerClass } from "./player_class_type";
// Mark import as potentially unused
declare type __keep_PlayerClass = PlayerClass;


export type Player = {
  playerId: number,
  name: string,
  spawnGracePeriodRemaining: number,
  playerClass: PlayerClass,
  level: number,
  exp: number,
  expForNextLevel: number,
  maxHp: number,
  hp: number,
  hpRegen: number,
  speed: number,
  armor: number,
  unspentUpgrades: number,
  rerolls: number,
  shieldCount: number,
  pvp: boolean,
  waypoint: DbVector2,
  hasWaypoint: boolean,
  position: DbVector2,
  radius: number,
  isBot: boolean,
};
/**
 * An object for generated helper functions.
 */
export const Player = {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    return __AlgebraicTypeValue.Product({
      elements: [
        { name: "playerId", algebraicType: __AlgebraicTypeValue.U32},
        { name: "name", algebraicType: __AlgebraicTypeValue.String},
        { name: "spawnGracePeriodRemaining", algebraicType: __AlgebraicTypeValue.U32},
        { name: "playerClass", algebraicType: PlayerClass.getTypeScriptAlgebraicType()},
        { name: "level", algebraicType: __AlgebraicTypeValue.U32},
        { name: "exp", algebraicType: __AlgebraicTypeValue.U32},
        { name: "expForNextLevel", algebraicType: __AlgebraicTypeValue.U32},
        { name: "maxHp", algebraicType: __AlgebraicTypeValue.F32},
        { name: "hp", algebraicType: __AlgebraicTypeValue.F32},
        { name: "hpRegen", algebraicType: __AlgebraicTypeValue.U32},
        { name: "speed", algebraicType: __AlgebraicTypeValue.F32},
        { name: "armor", algebraicType: __AlgebraicTypeValue.U32},
        { name: "unspentUpgrades", algebraicType: __AlgebraicTypeValue.U32},
        { name: "rerolls", algebraicType: __AlgebraicTypeValue.U32},
        { name: "shieldCount", algebraicType: __AlgebraicTypeValue.U32},
        { name: "pvp", algebraicType: __AlgebraicTypeValue.Bool},
        { name: "waypoint", algebraicType: DbVector2.getTypeScriptAlgebraicType()},
        { name: "hasWaypoint", algebraicType: __AlgebraicTypeValue.Bool},
        { name: "position", algebraicType: DbVector2.getTypeScriptAlgebraicType()},
        { name: "radius", algebraicType: __AlgebraicTypeValue.F32},
        { name: "isBot", algebraicType: __AlgebraicTypeValue.Bool},
      ]
    });
  },

  serialize(writer: __BinaryWriter, value: Player): void {
    __AlgebraicTypeValue.serializeValue(writer, Player.getTypeScriptAlgebraicType(), value);
  },

  deserialize(reader: __BinaryReader): Player {
    return __AlgebraicTypeValue.deserializeValue(reader, Player.getTypeScriptAlgebraicType());
  },

}

export default Player;


