// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  DbVector2,
  PlayerClass,
} from "./types";


export default __t.row({
  playerId: __t.u32().primaryKey().name("player_id"),
  name: __t.string(),
  spawnGracePeriodRemaining: __t.u32().name("spawn_grace_period_remaining"),
  get playerClass() {
    return PlayerClass.name("player_class");
  },
  level: __t.u32(),
  exp: __t.u32(),
  expForNextLevel: __t.u32().name("exp_for_next_level"),
  maxHp: __t.f32().name("max_hp"),
  hp: __t.f32(),
  hpRegen: __t.u32().name("hp_regen"),
  speed: __t.f32(),
  armor: __t.u32(),
  unspentUpgrades: __t.u32().name("unspent_upgrades"),
  rerolls: __t.u32(),
  shieldCount: __t.u32().name("shield_count"),
  pvp: __t.bool(),
  get waypoint() {
    return DbVector2;
  },
  hasWaypoint: __t.bool().name("has_waypoint"),
  get position() {
    return DbVector2;
  },
  radius: __t.f32(),
  isBot: __t.bool().name("is_bot"),
});
