// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  CallReducerFlags,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  DbContext,
  ErrorContextInterface,
  Event,
  EventContextInterface,
  Identity,
  ProductType,
  ProductTypeElement,
  ReducerEventContextInterface,
  SubscriptionBuilderImpl,
  SubscriptionEventContextInterface,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
} from "@clockworklabs/spacetimedb-sdk";
import { AttackType as __AttackType } from "./attack_type_type";

export type PlayerScheduledAttack = {
  scheduledId: bigint,
  playerId: number,
  attackType: __AttackType,
  skillLevel: number,
  parameterU: number,
  parameterI: number,
  attackCount: number,
  duration: number,
  projectiles: number,
  fireDelay: number,
  speed: number,
  piercing: boolean,
  radius: number,
  damage: number,
  armorPiercing: number,
  scheduledAt: { tag: "Interval", value: TimeDuration } | { tag: "Time", value: Timestamp },
};

/**
 * A namespace for generated helper functions.
 */
export namespace PlayerScheduledAttack {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("scheduledId", AlgebraicType.createU64Type()),
      new ProductTypeElement("playerId", AlgebraicType.createU32Type()),
      new ProductTypeElement("attackType", __AttackType.getTypeScriptAlgebraicType()),
      new ProductTypeElement("skillLevel", AlgebraicType.createU32Type()),
      new ProductTypeElement("parameterU", AlgebraicType.createU32Type()),
      new ProductTypeElement("parameterI", AlgebraicType.createI32Type()),
      new ProductTypeElement("attackCount", AlgebraicType.createU32Type()),
      new ProductTypeElement("duration", AlgebraicType.createU32Type()),
      new ProductTypeElement("projectiles", AlgebraicType.createU32Type()),
      new ProductTypeElement("fireDelay", AlgebraicType.createU32Type()),
      new ProductTypeElement("speed", AlgebraicType.createF32Type()),
      new ProductTypeElement("piercing", AlgebraicType.createBoolType()),
      new ProductTypeElement("radius", AlgebraicType.createF32Type()),
      new ProductTypeElement("damage", AlgebraicType.createU32Type()),
      new ProductTypeElement("armorPiercing", AlgebraicType.createU32Type()),
      new ProductTypeElement("scheduledAt", AlgebraicType.createScheduleAtType()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: PlayerScheduledAttack): void {
    PlayerScheduledAttack.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): PlayerScheduledAttack {
    return PlayerScheduledAttack.getTypeScriptAlgebraicType().deserialize(reader);
  }

}


