// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
import { SavedAttack } from "./saved_attack_type";
import { AttackType as __AttackType } from "./attack_type_type";

import { type EventContext, type Reducer, RemoteReducers, RemoteTables } from ".";

/**
 * Table handle for the table `saved_attacks`.
 *
 * Obtain a handle from the [`savedAttacks`] property on [`RemoteTables`],
 * like `ctx.db.savedAttacks`.
 *
 * Users are encouraged not to explicitly reference this type,
 * but to directly chain method calls,
 * like `ctx.db.savedAttacks.on_insert(...)`.
 */
export class SavedAttacksTableHandle {
  tableCache: TableCache<SavedAttack>;

  constructor(tableCache: TableCache<SavedAttack>) {
    this.tableCache = tableCache;
  }

  count(): number {
    return this.tableCache.count();
  }

  iter(): Iterable<SavedAttack> {
    return this.tableCache.iter();
  }
  /**
   * Access to the `savedAttackId` unique index on the table `saved_attacks`,
   * which allows point queries on the field of the same name
   * via the [`SavedAttacksSavedAttackIdUnique.find`] method.
   *
   * Users are encouraged not to explicitly reference this type,
   * but to directly chain method calls,
   * like `ctx.db.savedAttacks.savedAttackId().find(...)`.
   *
   * Get a handle on the `savedAttackId` unique index on the table `saved_attacks`.
   */
  savedAttackId = {
    // Find the subscribed row whose `savedAttackId` column value is equal to `col_val`,
    // if such a row is present in the client cache.
    find: (col_val: number): SavedAttack | undefined => {
      for (let row of this.tableCache.iter()) {
        if (deepEqual(row.savedAttackId, col_val)) {
          return row;
        }
      }
    },
  };

  onInsert = (cb: (ctx: EventContext, row: SavedAttack) => void) => {
    return this.tableCache.onInsert(cb);
  }

  removeOnInsert = (cb: (ctx: EventContext, row: SavedAttack) => void) => {
    return this.tableCache.removeOnInsert(cb);
  }

  onDelete = (cb: (ctx: EventContext, row: SavedAttack) => void) => {
    return this.tableCache.onDelete(cb);
  }

  removeOnDelete = (cb: (ctx: EventContext, row: SavedAttack) => void) => {
    return this.tableCache.removeOnDelete(cb);
  }

  // Updates are only defined for tables with primary keys.
  onUpdate = (cb: (ctx: EventContext, oldRow: SavedAttack, newRow: SavedAttack) => void) => {
    return this.tableCache.onUpdate(cb);
  }

  removeOnUpdate = (cb: (ctx: EventContext, onRow: SavedAttack, newRow: SavedAttack) => void) => {
    return this.tableCache.removeOnUpdate(cb);
  }}
