// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  buildId: __t.u32().primaryKey().name("build_id"),
  maxHp: __t.f32().name("max_hp"),
  armor: __t.u32(),
  speed: __t.f32(),
  hpRegen: __t.u32().name("hp_regen"),
});
