// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  CallReducerFlags,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  DbContext,
  ErrorContextInterface,
  Event,
  EventContextInterface,
  Identity,
  ProductType,
  ProductTypeElement,
  ReducerEventContextInterface,
  SubscriptionBuilderImpl,
  SubscriptionEventContextInterface,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
} from "@clockworklabs/spacetimedb-sdk";
import { SimonZombieWaveScheduler } from "./simon_zombie_wave_scheduler_type";
import { EventContext, Reducer, RemoteReducers, RemoteTables } from ".";

/**
 * Table handle for the table `simon_zombie_wave_scheduler`.
 *
 * Obtain a handle from the [`simonZombieWaveScheduler`] property on [`RemoteTables`],
 * like `ctx.db.simonZombieWaveScheduler`.
 *
 * Users are encouraged not to explicitly reference this type,
 * but to directly chain method calls,
 * like `ctx.db.simonZombieWaveScheduler.on_insert(...)`.
 */
export class SimonZombieWaveSchedulerTableHandle {
  tableCache: TableCache<SimonZombieWaveScheduler>;

  constructor(tableCache: TableCache<SimonZombieWaveScheduler>) {
    this.tableCache = tableCache;
  }

  count(): number {
    return this.tableCache.count();
  }

  iter(): Iterable<SimonZombieWaveScheduler> {
    return this.tableCache.iter();
  }
  /**
   * Access to the `scheduledId` unique index on the table `simon_zombie_wave_scheduler`,
   * which allows point queries on the field of the same name
   * via the [`SimonZombieWaveSchedulerScheduledIdUnique.find`] method.
   *
   * Users are encouraged not to explicitly reference this type,
   * but to directly chain method calls,
   * like `ctx.db.simonZombieWaveScheduler.scheduledId().find(...)`.
   *
   * Get a handle on the `scheduledId` unique index on the table `simon_zombie_wave_scheduler`.
   */
  scheduledId = {
    // Find the subscribed row whose `scheduledId` column value is equal to `col_val`,
    // if such a row is present in the client cache.
    find: (col_val: bigint): SimonZombieWaveScheduler | undefined => {
      for (let row of this.tableCache.iter()) {
        if (deepEqual(row.scheduledId, col_val)) {
          return row;
        }
      }
    },
  };

  onInsert = (cb: (ctx: EventContext, row: SimonZombieWaveScheduler) => void) => {
    return this.tableCache.onInsert(cb);
  }

  removeOnInsert = (cb: (ctx: EventContext, row: SimonZombieWaveScheduler) => void) => {
    return this.tableCache.removeOnInsert(cb);
  }

  onDelete = (cb: (ctx: EventContext, row: SimonZombieWaveScheduler) => void) => {
    return this.tableCache.onDelete(cb);
  }

  removeOnDelete = (cb: (ctx: EventContext, row: SimonZombieWaveScheduler) => void) => {
    return this.tableCache.removeOnDelete(cb);
  }

  // Updates are only defined for tables with primary keys.
  onUpdate = (cb: (ctx: EventContext, oldRow: SimonZombieWaveScheduler, newRow: SimonZombieWaveScheduler) => void) => {
    return this.tableCache.onUpdate(cb);
  }

  removeOnUpdate = (cb: (ctx: EventContext, onRow: SimonZombieWaveScheduler, newRow: SimonZombieWaveScheduler) => void) => {
    return this.tableCache.removeOnUpdate(cb);
  }}
