// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  CallReducerFlags,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  DbContext,
  ErrorContextInterface,
  Event,
  EventContextInterface,
  Identity,
  ProductType,
  ProductTypeElement,
  ReducerEventContextInterface,
  SubscriptionBuilderImpl,
  SubscriptionEventContextInterface,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
} from "@clockworklabs/spacetimedb-sdk";

import { AgnaFlamethrowerScheduler as __AgnaFlamethrowerScheduler } from "./agna_flamethrower_scheduler_type";

export type TriggerAgnaFlamethrowerAttack = {
  scheduler: __AgnaFlamethrowerScheduler,
};

/**
 * A namespace for generated helper functions.
 */
export namespace TriggerAgnaFlamethrowerAttack {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("scheduler", __AgnaFlamethrowerScheduler.getTypeScriptAlgebraicType()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: TriggerAgnaFlamethrowerAttack): void {
    TriggerAgnaFlamethrowerAttack.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): TriggerAgnaFlamethrowerAttack {
    return TriggerAgnaFlamethrowerAttack.getTypeScriptAlgebraicType().deserialize(reader);
  }

}

