// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Account = __t.object("Account", {
  identity: __t.identity(),
  name: __t.string(),
  currentPlayerId: __t.u32(),
  lastLogin: __t.timestamp(),
  get state() {
    return AccountState;
  },
  soulId: __t.u32(),
});
export type Account = __Infer<typeof Account>;

// The tagged union or sum type for the algebraic type `AccountState`.
export const AccountState = __t.enum("AccountState", {
  ChoosingName: __t.unit(),
  ChoosingClass: __t.unit(),
  Playing: __t.unit(),
  Dead: __t.unit(),
  Winner: __t.unit(),
  CurseCutscene: __t.unit(),
});
export type AccountState = __Infer<typeof AccountState>;

export const ActiveAttack = __t.object("ActiveAttack", {
  activeAttackId: __t.u32(),
  entityId: __t.u32(),
  playerId: __t.u32(),
  get attackType() {
    return AttackType;
  },
  idWithinBurst: __t.u32(),
  parameterU: __t.u32(),
  ticksElapsed: __t.u32(),
  damage: __t.u32(),
  radius: __t.f32(),
  piercing: __t.bool(),
});
export type ActiveAttack = __Infer<typeof ActiveAttack>;

export const ActiveAttackCleanup = __t.object("ActiveAttackCleanup", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  activeAttackId: __t.u32(),
});
export type ActiveAttackCleanup = __Infer<typeof ActiveAttackCleanup>;

export const ActiveMonsterAttack = __t.object("ActiveMonsterAttack", {
  activeMonsterAttackId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  get position() {
    return DbVector2;
  },
  get direction() {
    return DbVector2;
  },
  get monsterAttackType() {
    return MonsterAttackType;
  },
  piercing: __t.bool(),
  damage: __t.u32(),
  radius: __t.f32(),
  speed: __t.f32(),
  parameterU: __t.u32(),
  parameterF: __t.f32(),
  ticksElapsed: __t.u32(),
  fromShinyMonster: __t.bool(),
});
export type ActiveMonsterAttack = __Infer<typeof ActiveMonsterAttack>;

export const AgnaCandleBoltScheduler = __t.object("AgnaCandleBoltScheduler", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  candleMonsterId: __t.u32(),
  targetPlayerId: __t.u32(),
});
export type AgnaCandleBoltScheduler = __Infer<typeof AgnaCandleBoltScheduler>;

export const AgnaCandleScheduler = __t.object("AgnaCandleScheduler", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  bossMonsterId: __t.u32(),
  spawnId: __t.u64(),
});
export type AgnaCandleScheduler = __Infer<typeof AgnaCandleScheduler>;

export const AgnaCandleSpawn = __t.object("AgnaCandleSpawn", {
  spawnId: __t.u64(),
  bossMonsterId: __t.u32(),
  get position() {
    return DbVector2;
  },
  candleIndex: __t.u32(),
  candleMonsterId: __t.u32(),
});
export type AgnaCandleSpawn = __Infer<typeof AgnaCandleSpawn>;

export const AgnaDelayedOrbScheduler = __t.object("AgnaDelayedOrbScheduler", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  bossMonsterId: __t.u32(),
  targetPlayerId: __t.u32(),
  get circlePosition() {
    return DbVector2;
  },
  circleIndex: __t.u32(),
});
export type AgnaDelayedOrbScheduler = __Infer<typeof AgnaDelayedOrbScheduler>;

export const AgnaFireOrbScheduler = __t.object("AgnaFireOrbScheduler", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  bossMonsterId: __t.u32(),
  targetPlayerId: __t.u32(),
});
export type AgnaFireOrbScheduler = __Infer<typeof AgnaFireOrbScheduler>;

export const AgnaFlamethrowerScheduler = __t.object("AgnaFlamethrowerScheduler", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  bossMonsterId: __t.u32(),
  targetPlayerId: __t.u32(),
});
export type AgnaFlamethrowerScheduler = __Infer<typeof AgnaFlamethrowerScheduler>;

export const AgnaMagicCircle = __t.object("AgnaMagicCircle", {
  circleId: __t.u64(),
  bossMonsterId: __t.u32(),
  targetPlayerId: __t.u32(),
  circleIndex: __t.u32(),
  initialRotation: __t.f32(),
  ticksElapsed: __t.u32(),
  get position() {
    return DbVector2;
  },
});
export type AgnaMagicCircle = __Infer<typeof AgnaMagicCircle>;

export const AgnaPhase2FlamethrowerScheduler = __t.object("AgnaPhase2FlamethrowerScheduler", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  bossMonsterId: __t.u32(),
});
export type AgnaPhase2FlamethrowerScheduler = __Infer<typeof AgnaPhase2FlamethrowerScheduler>;

export const AgnaRitualCompletionCheck = __t.object("AgnaRitualCompletionCheck", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  bossMonsterId: __t.u32(),
});
export type AgnaRitualCompletionCheck = __Infer<typeof AgnaRitualCompletionCheck>;

export const AgnaSummoningCircleSpawner = __t.object("AgnaSummoningCircleSpawner", {
  scheduledId: __t.u64(),
  bossMonsterId: __t.u32(),
  spawnIntervalMs: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type AgnaSummoningCircleSpawner = __Infer<typeof AgnaSummoningCircleSpawner>;

export const AgnaTargetSwitchScheduler = __t.object("AgnaTargetSwitchScheduler", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  bossMonsterId: __t.u32(),
});
export type AgnaTargetSwitchScheduler = __Infer<typeof AgnaTargetSwitchScheduler>;

// The tagged union or sum type for the algebraic type `AiState`.
export const AiState = __t.enum("AiState", {
  Default: __t.unit(),
  BossEnderIdle: __t.unit(),
  BossEnderChase: __t.unit(),
  BossEnderDance: __t.unit(),
  BossEnderVanish: __t.unit(),
  BossEnderLurk: __t.unit(),
  BossEnderTeleport: __t.unit(),
  BossEnderTransform: __t.unit(),
  Stationary: __t.unit(),
  BossAgnaIdle: __t.unit(),
  BossAgnaFlamethrower: __t.unit(),
  BossAgnaMagicCircle: __t.unit(),
  BossAgnaRitualMatch: __t.unit(),
  BossAgnaRitualWick: __t.unit(),
  BossAgnaRitualFailed: __t.unit(),
  BossAgnaRitualComplete: __t.unit(),
  BossSimonIdle: __t.unit(),
  BossSimonToxicSpray: __t.unit(),
  BossSimonZombieWave: __t.unit(),
  BossSimonTransform: __t.unit(),
  BossSimonChemicalBoltPattern: __t.unit(),
  BossSimonToxicZonePattern: __t.unit(),
  BossSimonPhase2Transform: __t.unit(),
});
export type AiState = __Infer<typeof AiState>;

export const AttackBurstCooldown = __t.object("AttackBurstCooldown", {
  scheduledId: __t.u64(),
  playerId: __t.u32(),
  get attackType() {
    return AttackType;
  },
  remainingShots: __t.u32(),
  parameterU: __t.u32(),
  parameterI: __t.i32(),
  scheduledAt: __t.scheduleAt(),
});
export type AttackBurstCooldown = __Infer<typeof AttackBurstCooldown>;

export const AttackData = __t.object("AttackData", {
  attackId: __t.u32(),
  get attackType() {
    return AttackType;
  },
  name: __t.string(),
  cooldown: __t.u32(),
  duration: __t.u32(),
  projectiles: __t.u32(),
  fireDelay: __t.u32(),
  speed: __t.f32(),
  piercing: __t.bool(),
  radius: __t.f32(),
  damage: __t.u32(),
  armorPiercing: __t.u32(),
});
export type AttackData = __Infer<typeof AttackData>;

// The tagged union or sum type for the algebraic type `AttackType`.
export const AttackType = __t.enum("AttackType", {
  Sword: __t.unit(),
  Wand: __t.unit(),
  Knives: __t.unit(),
  Shield: __t.unit(),
  ThunderHorn: __t.unit(),
  AngelStaff: __t.unit(),
  Football: __t.unit(),
  Cards: __t.unit(),
  Dumbbell: __t.unit(),
  Garlic: __t.unit(),
  Volleyball: __t.unit(),
  Joint: __t.unit(),
});
export type AttackType = __Infer<typeof AttackType>;

export const Bestiary = __t.object("Bestiary", {
  bestiaryId: __t.u32(),
  get monsterType() {
    return MonsterType;
  },
  tier: __t.u32(),
  maxHp: __t.u32(),
  speed: __t.f32(),
  atk: __t.f32(),
  radius: __t.f32(),
});
export type Bestiary = __Infer<typeof Bestiary>;

export const BossAgnaLastPattern = __t.object("BossAgnaLastPattern", {
  monsterId: __t.u32(),
  get lastPattern() {
    return AiState;
  },
});
export type BossAgnaLastPattern = __Infer<typeof BossAgnaLastPattern>;

export const BossEnderLastPattern = __t.object("BossEnderLastPattern", {
  monsterId: __t.u32(),
  get lastPattern() {
    return AiState;
  },
});
export type BossEnderLastPattern = __Infer<typeof BossEnderLastPattern>;

export const BossPhase2Timer = __t.object("BossPhase2Timer", {
  scheduledId: __t.u64(),
  get position() {
    return DbVector2;
  },
  scheduledAt: __t.scheduleAt(),
});
export type BossPhase2Timer = __Infer<typeof BossPhase2Timer>;

export const BossSelection = __t.object("BossSelection", {
  id: __t.u32(),
  get bossType() {
    return BossType;
  },
});
export type BossSelection = __Infer<typeof BossSelection>;

export const BossSimonLastPattern = __t.object("BossSimonLastPattern", {
  monsterId: __t.u32(),
  get lastPattern() {
    return AiState;
  },
});
export type BossSimonLastPattern = __Infer<typeof BossSimonLastPattern>;

export const BossSpawnTimer = __t.object("BossSpawnTimer", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  sessionStartTime: __t.timestamp(),
});
export type BossSpawnTimer = __Infer<typeof BossSpawnTimer>;

export const BossTargetSwitchScheduler = __t.object("BossTargetSwitchScheduler", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  bossMonsterId: __t.u32(),
});
export type BossTargetSwitchScheduler = __Infer<typeof BossTargetSwitchScheduler>;

// The tagged union or sum type for the algebraic type `BossType`.
export const BossType = __t.enum("BossType", {
  Ender: __t.unit(),
  Agna: __t.unit(),
  Simon: __t.unit(),
});
export type BossType = __Infer<typeof BossType>;

export const ChaosBallScheduler = __t.object("ChaosBallScheduler", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  bossMonsterId: __t.u32(),
});
export type ChaosBallScheduler = __Infer<typeof ChaosBallScheduler>;

export const ChemicalBoltScheduler = __t.object("ChemicalBoltScheduler", {
  scheduledId: __t.u64(),
  bossMonsterId: __t.u32(),
  targetPlayerId: __t.u32(),
  scheduledAt: __t.scheduleAt(),
});
export type ChemicalBoltScheduler = __Infer<typeof ChemicalBoltScheduler>;

export const ChosenUpgradeData = __t.object("ChosenUpgradeData", {
  chosenUpgradeId: __t.u32(),
  playerId: __t.u32(),
  get upgradeType() {
    return UpgradeType;
  },
  isAttackUpgrade: __t.bool(),
  value: __t.u32(),
  attackType: __t.u32(),
  damage: __t.u32(),
  cooldownRatio: __t.u32(),
  projectiles: __t.u32(),
  speed: __t.u32(),
  radius: __t.u32(),
  isNewAttack: __t.bool(),
});
export type ChosenUpgradeData = __Infer<typeof ChosenUpgradeData>;

export const ClassData = __t.object("ClassData", {
  classId: __t.u32(),
  get playerClass() {
    return PlayerClass;
  },
  maxHp: __t.i32(),
  armor: __t.i32(),
  speed: __t.f32(),
  get startingAttackType() {
    return AttackType;
  },
});
export type ClassData = __Infer<typeof ClassData>;

export const Config = __t.object("Config", {
  id: __t.u32(),
  worldSize: __t.u32(),
  gameTickRate: __t.u32(),
  maxMonsters: __t.u32(),
  playerSpawnGracePeriod: __t.u32(),
  monsterHitCleanupDelay: __t.u32(),
  monsterWaveSize: __t.u32(),
});
export type Config = __Infer<typeof Config>;

export const Curse = __t.object("Curse", {
  curseId: __t.u64(),
  get curseType() {
    return CurseType;
  },
});
export type Curse = __Infer<typeof Curse>;

export const CurseTransitionTimer = __t.object("CurseTransitionTimer", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  identity: __t.identity(),
});
export type CurseTransitionTimer = __Infer<typeof CurseTransitionTimer>;

// The tagged union or sum type for the algebraic type `CurseType`.
export const CurseType = __t.enum("CurseType", {
  MonsterMoreHp: __t.unit(),
  MonsterMoreDamage: __t.unit(),
  MonsterMoreSpeed: __t.unit(),
  MonsterHealthRegen: __t.unit(),
  CursedMonstersSpawn: __t.unit(),
  NoFreeReroll: __t.unit(),
  NoHealOnLevelUp: __t.unit(),
  NegativeHealthRegen: __t.unit(),
  PlayersStartLessHp: __t.unit(),
  PlayersStartLessSpeed: __t.unit(),
  NoDiceDrops: __t.unit(),
  NoFoodDrops: __t.unit(),
  NoBoosterPackDrops: __t.unit(),
  NoStructureLoot: __t.unit(),
  OneLessVoidChest: __t.unit(),
  OneLessVoidChestSecond: __t.unit(),
  MonstersDropFewerGems: __t.unit(),
  BossAppearsSooner: __t.unit(),
  DeadlierBosses: __t.unit(),
  DeadlierBossesTwo: __t.unit(),
  Scaling: __t.unit(),
});
export type CurseType = __Infer<typeof CurseType>;

export const DbVector2 = __t.object("DbVector2", {
  x: __t.f32(),
  y: __t.f32(),
});
export type DbVector2 = __Infer<typeof DbVector2>;

export const DeadPlayer = __t.object("DeadPlayer", {
  playerId: __t.u32(),
  name: __t.string(),
  isTrueSurvivor: __t.bool(),
});
export type DeadPlayer = __Infer<typeof DeadPlayer>;

export const DeadPlayerTransitionTimer = __t.object("DeadPlayerTransitionTimer", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  identity: __t.identity(),
});
export type DeadPlayerTransitionTimer = __Infer<typeof DeadPlayerTransitionTimer>;

export const EnderBoltScheduler = __t.object("EnderBoltScheduler", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  bossMonsterId: __t.u32(),
});
export type EnderBoltScheduler = __Infer<typeof EnderBoltScheduler>;

export const EnderClawSpawner = __t.object("EnderClawSpawner", {
  scheduledId: __t.u64(),
  bossMonsterId: __t.u32(),
  spawnIntervalMs: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type EnderClawSpawner = __Infer<typeof EnderClawSpawner>;

export const EnderScytheScheduler = __t.object("EnderScytheScheduler", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  bossMonsterId: __t.u32(),
  baseRotation: __t.f32(),
});
export type EnderScytheScheduler = __Infer<typeof EnderScytheScheduler>;

export const EnderScytheSpawnScheduler = __t.object("EnderScytheSpawnScheduler", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  bossMonsterId: __t.u32(),
  baseRotation: __t.f32(),
});
export type EnderScytheSpawnScheduler = __Infer<typeof EnderScytheSpawnScheduler>;

export const Entity = __t.object("Entity", {
  entityId: __t.u32(),
  get position() {
    return DbVector2;
  },
  get direction() {
    return DbVector2;
  },
  radius: __t.f32(),
  get waypoint() {
    return DbVector2;
  },
  hasWaypoint: __t.bool(),
});
export type Entity = __Infer<typeof Entity>;

export const ExpConfig = __t.object("ExpConfig", {
  configId: __t.u32(),
  expSmallGem: __t.u32(),
  expMediumGem: __t.u32(),
  expLargeGem: __t.u32(),
  expHugeGem: __t.u32(),
  baseExpPerLevel: __t.u32(),
  levelExpFactor: __t.f32(),
  gemRadius: __t.f32(),
});
export type ExpConfig = __Infer<typeof ExpConfig>;

export const FoundLoreScrolls = __t.object("FoundLoreScrolls", {
  pickupId: __t.u64(),
  playerId: __t.u32(),
  scrollId: __t.u32(),
});
export type FoundLoreScrolls = __Infer<typeof FoundLoreScrolls>;

export const GameState = __t.object("GameState", {
  id: __t.u32(),
  bossActive: __t.bool(),
  bossPhase: __t.u32(),
  bossMonsterId: __t.u32(),
  get bossType() {
    return BossType;
  },
  normalSpawningPaused: __t.bool(),
  gameStartTime: __t.timestamp(),
});
export type GameState = __Infer<typeof GameState>;

export const GameTickTimer = __t.object("GameTickTimer", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type GameTickTimer = __Infer<typeof GameTickTimer>;

export const Gem = __t.object("Gem", {
  gemId: __t.u32(),
  entityId: __t.u32(),
  get level() {
    return GemLevel;
  },
  value: __t.u32(),
});
export type Gem = __Infer<typeof Gem>;

// The tagged union or sum type for the algebraic type `GemLevel`.
export const GemLevel = __t.enum("GemLevel", {
  Small: __t.unit(),
  Medium: __t.unit(),
  Large: __t.unit(),
  Huge: __t.unit(),
  Soul: __t.unit(),
  Fries: __t.unit(),
  Dice: __t.unit(),
  BoosterPack: __t.unit(),
  LoreScroll: __t.unit(),
});
export type GemLevel = __Infer<typeof GemLevel>;

export const GuaranteedVoidChestSpawn = __t.object("GuaranteedVoidChestSpawn", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  chestIndex: __t.u32(),
});
export type GuaranteedVoidChestSpawn = __Infer<typeof GuaranteedVoidChestSpawn>;

export const HealthRegenScheduler = __t.object("HealthRegenScheduler", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type HealthRegenScheduler = __Infer<typeof HealthRegenScheduler>;

export const HealthRegenTimer = __t.object("HealthRegenTimer", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type HealthRegenTimer = __Infer<typeof HealthRegenTimer>;

export const ImpAttackScheduler = __t.object("ImpAttackScheduler", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  impMonsterId: __t.u32(),
});
export type ImpAttackScheduler = __Infer<typeof ImpAttackScheduler>;

export const LootCapsules = __t.object("LootCapsules", {
  capsuleId: __t.u64(),
  get startPosition() {
    return DbVector2;
  },
  get endPosition() {
    return DbVector2;
  },
  get lootdropId() {
    return GemLevel;
  },
  scheduledAt: __t.scheduleAt(),
});
export type LootCapsules = __Infer<typeof LootCapsules>;

// The tagged union or sum type for the algebraic type `MonsterAttackType`.
export const MonsterAttackType = __t.enum("MonsterAttackType", {
  ImpBolt: __t.unit(),
  EnderBolt: __t.unit(),
  EnderScytheSpawn: __t.unit(),
  EnderScythe: __t.unit(),
  ChaosBall: __t.unit(),
  VoidZone: __t.unit(),
  AgnaFlamethrowerJet: __t.unit(),
  AgnaOrbSpawn: __t.unit(),
  AgnaFireOrb: __t.unit(),
  AgnaCandleBolt: __t.unit(),
  AgnaPhase2FlameJet: __t.unit(),
  AgnaGroundFlame: __t.unit(),
  SimonChemicalBolt: __t.unit(),
  SimonToxicZone: __t.unit(),
  SimonToxicSpray: __t.unit(),
});
export type MonsterAttackType = __Infer<typeof MonsterAttackType>;

export const MonsterBoid = __t.object("MonsterBoid", {
  monsterId: __t.u32(),
  get position() {
    return DbVector2;
  },
});
export type MonsterBoid = __Infer<typeof MonsterBoid>;

export const MonsterDamage = __t.object("MonsterDamage", {
  damageId: __t.u32(),
  monsterId: __t.u32(),
  attackEntityId: __t.u32(),
});
export type MonsterDamage = __Infer<typeof MonsterDamage>;

export const MonsterHealthRegenTimer = __t.object("MonsterHealthRegenTimer", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type MonsterHealthRegenTimer = __Infer<typeof MonsterHealthRegenTimer>;

export const MonsterHitCleanup = __t.object("MonsterHitCleanup", {
  scheduledId: __t.u64(),
  damageId: __t.u32(),
  scheduledAt: __t.scheduleAt(),
});
export type MonsterHitCleanup = __Infer<typeof MonsterHitCleanup>;

export const MonsterSpawnTimer = __t.object("MonsterSpawnTimer", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type MonsterSpawnTimer = __Infer<typeof MonsterSpawnTimer>;

export const MonsterSpawners = __t.object("MonsterSpawners", {
  scheduledId: __t.u64(),
  get position() {
    return DbVector2;
  },
  get monsterType() {
    return MonsterType;
  },
  scheduledAt: __t.scheduleAt(),
});
export type MonsterSpawners = __Infer<typeof MonsterSpawners>;

export const MonsterStateChange = __t.object("MonsterStateChange", {
  scheduledId: __t.u64(),
  targetMonsterId: __t.u32(),
  get targetState() {
    return AiState;
  },
  scheduledAt: __t.scheduleAt(),
});
export type MonsterStateChange = __Infer<typeof MonsterStateChange>;

// The tagged union or sum type for the algebraic type `MonsterType`.
export const MonsterType = __t.enum("MonsterType", {
  Rat: __t.unit(),
  Slime: __t.unit(),
  Bat: __t.unit(),
  Orc: __t.unit(),
  Imp: __t.unit(),
  Zombie: __t.unit(),
  VoidChest: __t.unit(),
  EnderClaw: __t.unit(),
  BossEnderPhase1: __t.unit(),
  BossEnderPhase2: __t.unit(),
  BossAgnaPhase1: __t.unit(),
  BossAgnaPhase2: __t.unit(),
  BossSimonPhase1: __t.unit(),
  BossSimonPhase2: __t.unit(),
  AgnaCandle: __t.unit(),
  Crate: __t.unit(),
  Tree: __t.unit(),
  Statue: __t.unit(),
});
export type MonsterType = __Infer<typeof MonsterType>;

// The tagged union or sum type for the algebraic type `MonsterVariant`.
export const MonsterVariant = __t.enum("MonsterVariant", {
  Default: __t.unit(),
  Shiny: __t.unit(),
  Cursed: __t.unit(),
});
export type MonsterVariant = __Infer<typeof MonsterVariant>;

export const Monsters = __t.object("Monsters", {
  monsterId: __t.u32(),
  get bestiaryId() {
    return MonsterType;
  },
  get variant() {
    return MonsterVariant;
  },
  hp: __t.u32(),
  maxHp: __t.u32(),
  atk: __t.f32(),
  speed: __t.f32(),
  targetPlayerId: __t.u32(),
  get aiState() {
    return AiState;
  },
  radius: __t.f32(),
  get spawnPosition() {
    return DbVector2;
  },
});
export type Monsters = __Infer<typeof Monsters>;

export const Player = __t.object("Player", {
  playerId: __t.u32(),
  name: __t.string(),
  spawnGracePeriodRemaining: __t.u32(),
  get playerClass() {
    return PlayerClass;
  },
  level: __t.u32(),
  exp: __t.u32(),
  expForNextLevel: __t.u32(),
  maxHp: __t.f32(),
  hp: __t.f32(),
  hpRegen: __t.u32(),
  speed: __t.f32(),
  armor: __t.u32(),
  unspentUpgrades: __t.u32(),
  rerolls: __t.u32(),
  shieldCount: __t.u32(),
  pvp: __t.bool(),
  get waypoint() {
    return DbVector2;
  },
  hasWaypoint: __t.bool(),
  get position() {
    return DbVector2;
  },
  radius: __t.f32(),
  isBot: __t.bool(),
});
export type Player = __Infer<typeof Player>;

// The tagged union or sum type for the algebraic type `PlayerClass`.
export const PlayerClass = __t.enum("PlayerClass", {
  Fighter: __t.unit(),
  Rogue: __t.unit(),
  Mage: __t.unit(),
  Paladin: __t.unit(),
  Valkyrie: __t.unit(),
  Priest: __t.unit(),
  Football: __t.unit(),
  Gambler: __t.unit(),
  Athlete: __t.unit(),
  Gourmand: __t.unit(),
  Volleyball: __t.unit(),
  Stoner: __t.unit(),
});
export type PlayerClass = __Infer<typeof PlayerClass>;

export const PlayerScheduledAttack = __t.object("PlayerScheduledAttack", {
  scheduledId: __t.u64(),
  playerId: __t.u32(),
  get attackType() {
    return AttackType;
  },
  skillLevel: __t.u32(),
  parameterU: __t.u32(),
  parameterI: __t.i32(),
  attackCount: __t.u32(),
  cooldown: __t.u32(),
  duration: __t.u32(),
  projectiles: __t.u32(),
  fireDelay: __t.u32(),
  speed: __t.f32(),
  piercing: __t.bool(),
  radius: __t.f32(),
  damage: __t.u32(),
  armorPiercing: __t.u32(),
  scheduledAt: __t.scheduleAt(),
});
export type PlayerScheduledAttack = __Infer<typeof PlayerScheduledAttack>;

export const SavedAttack = __t.object("SavedAttack", {
  savedAttackId: __t.u32(),
  get attackType() {
    return AttackType;
  },
  skillLevel: __t.u32(),
  parameterU: __t.u32(),
  parameterI: __t.i32(),
  attackCount: __t.u32(),
  cooldown: __t.u32(),
  duration: __t.u32(),
  projectiles: __t.u32(),
  fireDelay: __t.u32(),
  speed: __t.f32(),
  piercing: __t.bool(),
  radius: __t.f32(),
  damage: __t.u32(),
  armorPiercing: __t.u32(),
});
export type SavedAttack = __Infer<typeof SavedAttack>;

export const SavedBuild = __t.object("SavedBuild", {
  buildId: __t.u32(),
  maxHp: __t.f32(),
  armor: __t.u32(),
  speed: __t.f32(),
  hpRegen: __t.u32(),
});
export type SavedBuild = __Infer<typeof SavedBuild>;

export const SimonZombieWaveScheduler = __t.object("SimonZombieWaveScheduler", {
  scheduledId: __t.u64(),
  bossMonsterId: __t.u32(),
  scheduledAt: __t.scheduleAt(),
});
export type SimonZombieWaveScheduler = __Infer<typeof SimonZombieWaveScheduler>;

export const ToxicSprayScheduler = __t.object("ToxicSprayScheduler", {
  scheduledId: __t.u64(),
  bossMonsterId: __t.u32(),
  scheduledAt: __t.scheduleAt(),
  sprayCount: __t.u32(),
});
export type ToxicSprayScheduler = __Infer<typeof ToxicSprayScheduler>;

export const ToxicZoneScheduler = __t.object("ToxicZoneScheduler", {
  scheduledId: __t.u64(),
  bossMonsterId: __t.u32(),
  scheduledAt: __t.scheduleAt(),
});
export type ToxicZoneScheduler = __Infer<typeof ToxicZoneScheduler>;

export const UpgradeOptionData = __t.object("UpgradeOptionData", {
  upgradeId: __t.u32(),
  playerId: __t.u32(),
  upgradeIndex: __t.u32(),
  get upgradeType() {
    return UpgradeType;
  },
  isAttackUpgrade: __t.bool(),
  value: __t.u32(),
  attackType: __t.u32(),
  damage: __t.u32(),
  cooldownRatio: __t.u32(),
  projectiles: __t.u32(),
  speed: __t.u32(),
  radius: __t.u32(),
  isNewAttack: __t.bool(),
});
export type UpgradeOptionData = __Infer<typeof UpgradeOptionData>;

// The tagged union or sum type for the algebraic type `UpgradeType`.
export const UpgradeType = __t.enum("UpgradeType", {
  MaxHp: __t.unit(),
  HpRegen: __t.unit(),
  Speed: __t.unit(),
  Armor: __t.unit(),
  AttackSword: __t.unit(),
  AttackWand: __t.unit(),
  AttackKnives: __t.unit(),
  AttackShield: __t.unit(),
  AttackThunderHorn: __t.unit(),
  AttackAngelStaff: __t.unit(),
  AttackFootball: __t.unit(),
  AttackCards: __t.unit(),
  AttackDumbbell: __t.unit(),
  AttackGarlic: __t.unit(),
  AttackVolleyball: __t.unit(),
  AttackJoint: __t.unit(),
});
export type UpgradeType = __Infer<typeof UpgradeType>;

export const VoidZoneScheduler = __t.object("VoidZoneScheduler", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  bossMonsterId: __t.u32(),
});
export type VoidZoneScheduler = __Infer<typeof VoidZoneScheduler>;

export const WinnerTransitionTimer = __t.object("WinnerTransitionTimer", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  identity: __t.identity(),
});
export type WinnerTransitionTimer = __Infer<typeof WinnerTransitionTimer>;

export const World = __t.object("World", {
  worldId: __t.u32(),
  tickCount: __t.u32(),
  lastTickTime: __t.timestamp(),
  averageTickMs: __t.f64(),
  minTickMs: __t.f64(),
  maxTickMs: __t.f64(),
  timingSamplesCollected: __t.u32(),
});
export type World = __Infer<typeof World>;

