// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
} from "spacetimedb";

export type MaxHp = { tag: "MaxHp" };
export type HpRegen = { tag: "HpRegen" };
export type Speed = { tag: "Speed" };
export type Armor = { tag: "Armor" };
export type AttackSword = { tag: "AttackSword" };
export type AttackWand = { tag: "AttackWand" };
export type AttackKnives = { tag: "AttackKnives" };
export type AttackShield = { tag: "AttackShield" };
export type AttackThunderHorn = { tag: "AttackThunderHorn" };
export type AttackAngelStaff = { tag: "AttackAngelStaff" };
export type AttackFootball = { tag: "AttackFootball" };
export type AttackCards = { tag: "AttackCards" };
export type AttackDumbbell = { tag: "AttackDumbbell" };
export type AttackGarlic = { tag: "AttackGarlic" };
export type AttackVolleyball = { tag: "AttackVolleyball" };
export type AttackJoint = { tag: "AttackJoint" };

