// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  UpgradeType,
} from "./types";


export default __t.row({
  upgradeId: __t.u32().primaryKey().name("upgrade_id"),
  playerId: __t.u32().name("player_id"),
  upgradeIndex: __t.u32().name("upgrade_index"),
  get upgradeType() {
    return UpgradeType.name("upgrade_type");
  },
  isAttackUpgrade: __t.bool().name("is_attack_upgrade"),
  value: __t.u32(),
  attackType: __t.u32().name("attack_type"),
  damage: __t.u32(),
  cooldownRatio: __t.u32().name("cooldown_ratio"),
  projectiles: __t.u32(),
  speed: __t.u32(),
  radius: __t.u32(),
  isNewAttack: __t.bool().name("is_new_attack"),
});
