// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
} from "spacetimedb";
import * as UpgradeTypeVariants from './upgrade_type_variants'

// The tagged union or sum type for the algebraic type `UpgradeType`.
export type UpgradeType = UpgradeTypeVariants.MaxHp |
  UpgradeTypeVariants.HpRegen |
  UpgradeTypeVariants.Speed |
  UpgradeTypeVariants.Armor |
  UpgradeTypeVariants.AttackSword |
  UpgradeTypeVariants.AttackWand |
  UpgradeTypeVariants.AttackKnives |
  UpgradeTypeVariants.AttackShield |
  UpgradeTypeVariants.AttackThunderHorn |
  UpgradeTypeVariants.AttackAngelStaff |
  UpgradeTypeVariants.AttackFootball |
  UpgradeTypeVariants.AttackCards |
  UpgradeTypeVariants.AttackDumbbell |
  UpgradeTypeVariants.AttackGarlic |
  UpgradeTypeVariants.AttackVolleyball |
  UpgradeTypeVariants.AttackJoint;

// A value with helper functions to construct the type.
export const UpgradeType = {
  // Helper functions for constructing each variant of the tagged union.
  // ```
  // const foo = Foo.A(42);
  // assert!(foo.tag === "A");
  // assert!(foo.value === 42);
  // ```
  MaxHp: { tag: "MaxHp" } as const,
  HpRegen: { tag: "HpRegen" } as const,
  Speed: { tag: "Speed" } as const,
  Armor: { tag: "Armor" } as const,
  AttackSword: { tag: "AttackSword" } as const,
  AttackWand: { tag: "AttackWand" } as const,
  AttackKnives: { tag: "AttackKnives" } as const,
  AttackShield: { tag: "AttackShield" } as const,
  AttackThunderHorn: { tag: "AttackThunderHorn" } as const,
  AttackAngelStaff: { tag: "AttackAngelStaff" } as const,
  AttackFootball: { tag: "AttackFootball" } as const,
  AttackCards: { tag: "AttackCards" } as const,
  AttackDumbbell: { tag: "AttackDumbbell" } as const,
  AttackGarlic: { tag: "AttackGarlic" } as const,
  AttackVolleyball: { tag: "AttackVolleyball" } as const,
  AttackJoint: { tag: "AttackJoint" } as const,

  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    return __AlgebraicTypeValue.Sum({
      variants: [
        { name: "MaxHp", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "HpRegen", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "Speed", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "Armor", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "AttackSword", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "AttackWand", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "AttackKnives", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "AttackShield", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "AttackThunderHorn", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "AttackAngelStaff", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "AttackFootball", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "AttackCards", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "AttackDumbbell", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "AttackGarlic", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "AttackVolleyball", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "AttackJoint", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
      ]
    });
  },

  serialize(writer: __BinaryWriter, value: UpgradeType): void {
      __AlgebraicTypeValue.serializeValue(writer, UpgradeType.getTypeScriptAlgebraicType(), value);
  },

  deserialize(reader: __BinaryReader): UpgradeType {
      return __AlgebraicTypeValue.deserializeValue(reader, UpgradeType.getTypeScriptAlgebraicType());
  },

}

export default UpgradeType;


