// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  worldId: __t.u32().primaryKey().name("world_id"),
  tickCount: __t.u32().name("tick_count"),
  lastTickTime: __t.timestamp().name("last_tick_time"),
  averageTickMs: __t.f64().name("average_tick_ms"),
  minTickMs: __t.f64().name("min_tick_ms"),
  maxTickMs: __t.f64().name("max_tick_ms"),
  timingSamplesCollected: __t.u32().name("timing_samples_collected"),
});
