// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  CallReducerFlags,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  DbContext,
  ErrorContextInterface,
  Event,
  EventContextInterface,
  Identity,
  ProductType,
  ProductTypeElement,
  ReducerEventContextInterface,
  SubscriptionBuilderImpl,
  SubscriptionEventContextInterface,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
} from "@clockworklabs/spacetimedb-sdk";
import { FoundLoreScrolls } from "./found_lore_scrolls_type";
import { EventContext, Reducer, RemoteReducers, RemoteTables } from ".";

/**
 * Table handle for the table `found_lore_scrolls`.
 *
 * Obtain a handle from the [`foundLoreScrolls`] property on [`RemoteTables`],
 * like `ctx.db.foundLoreScrolls`.
 *
 * Users are encouraged not to explicitly reference this type,
 * but to directly chain method calls,
 * like `ctx.db.foundLoreScrolls.on_insert(...)`.
 */
export class FoundLoreScrollsTableHandle {
  tableCache: TableCache<FoundLoreScrolls>;

  constructor(tableCache: TableCache<FoundLoreScrolls>) {
    this.tableCache = tableCache;
  }

  count(): number {
    return this.tableCache.count();
  }

  iter(): Iterable<FoundLoreScrolls> {
    return this.tableCache.iter();
  }
  /**
   * Access to the `pickupId` unique index on the table `found_lore_scrolls`,
   * which allows point queries on the field of the same name
   * via the [`FoundLoreScrollsPickupIdUnique.find`] method.
   *
   * Users are encouraged not to explicitly reference this type,
   * but to directly chain method calls,
   * like `ctx.db.foundLoreScrolls.pickupId().find(...)`.
   *
   * Get a handle on the `pickupId` unique index on the table `found_lore_scrolls`.
   */
  pickupId = {
    // Find the subscribed row whose `pickupId` column value is equal to `col_val`,
    // if such a row is present in the client cache.
    find: (col_val: bigint): FoundLoreScrolls | undefined => {
      for (let row of this.tableCache.iter()) {
        if (deepEqual(row.pickupId, col_val)) {
          return row;
        }
      }
    },
  };

  onInsert = (cb: (ctx: EventContext, row: FoundLoreScrolls) => void) => {
    return this.tableCache.onInsert(cb);
  }

  removeOnInsert = (cb: (ctx: EventContext, row: FoundLoreScrolls) => void) => {
    return this.tableCache.removeOnInsert(cb);
  }

  onDelete = (cb: (ctx: EventContext, row: FoundLoreScrolls) => void) => {
    return this.tableCache.onDelete(cb);
  }

  removeOnDelete = (cb: (ctx: EventContext, row: FoundLoreScrolls) => void) => {
    return this.tableCache.removeOnDelete(cb);
  }

  // Updates are only defined for tables with primary keys.
  onUpdate = (cb: (ctx: EventContext, oldRow: FoundLoreScrolls, newRow: FoundLoreScrolls) => void) => {
    return this.tableCache.onUpdate(cb);
  }

  removeOnUpdate = (cb: (ctx: EventContext, onRow: FoundLoreScrolls, newRow: FoundLoreScrolls) => void) => {
    return this.tableCache.removeOnUpdate(cb);
  }}
